[package]
name = "miniworld-id-studio-mit"
version = "1.1.0-beta.2"
description = "Editor MIT completamente local de activadores y Lua para Mini World"
authors = ["Mini World ID"]
edition = "2021"

[lib]
name = "miniworld_id_studio_mit_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-store = "2"
regex = "1"
serde = { version = "1", features = ["derive"] }
