import type{StudioAction}from'./studio-core';
export function actionAtPath(actions:StudioAction[],path:string):StudioAction|undefined{const indexes=path.split('.').map(Number);let list=actions,action:StudioAction|undefined;for(let depth=0;depth<indexes.length;depth+=1){const index=indexes[depth];if(!Number.isInteger(index)||index<0||index>=list.length)return undefined;action=list[index];if(depth<indexes.length-1){if(!action.children)return undefined;list=action.children}}return action}
export function actionContainerAtPath(actions:StudioAction[],path:string):{list:StudioAction[];index:number}|undefined{const indexes=path.split('.').map(Number),index=indexes.pop();if(index===undefined||!Number.isInteger(index)||index<0)return undefined;let list=actions;for(const parentIndex of indexes){const parent=list[parentIndex];if(!parent?.children)return undefined;list=parent.children}return index<list.length?{list,index}:undefined}
export function findActionPath(actions:StudioAction[],id:string):string|undefined{const walk=(items:StudioAction[],prefix:string):string|undefined=>{for(let index=0;index<items.length;index+=1){const path=prefix?`${prefix}.${index}`:String(index),action=items[index];if(action.id===id)return path;const nested=action.children?walk(action.children,path):undefined;if(nested)return nested}return undefined};return walk(actions,'')}
export function removeActionAtPath(actions:StudioAction[],path:string):StudioAction|undefined{const container=actionContainerAtPath(actions,path);return container?.list.splice(container.index,1)[0]}
export function moveActionByOffset(actions:StudioAction[],path:string,offset:-1|1):boolean{const container=actionContainerAtPath(actions,path);if(!container)return false;const target=container.index+offset;if(target<0||target>=container.list.length)return false;const[action]=container.list.splice(container.index,1);container.list.splice(target,0,action);return true}
export function moveActionBefore(actions:StudioAction[],sourcePath:string,targetPath:string):boolean{const source=actionAtPath(actions,sourcePath),target=actionAtPath(actions,targetPath);if(!source||!target||source===target||targetPath.startsWith(`${sourcePath}.`))return false;const removed=removeActionAtPath(actions,sourcePath);if(!removed)return false;const currentTarget=findActionPath(actions,target.id),container=currentTarget?actionContainerAtPath(actions,currentTarget):undefined;if(!container)return false;container.list.splice(container.index,0,removed);return true}
export function moveActionToRootEnd(actions:StudioAction[],sourcePath:string):boolean{const source=actionAtPath(actions,sourcePath);if(!source)return false;const removed=removeActionAtPath(actions,sourcePath);if(!removed)return false;actions.push(removed);return true}
export function insertActionAfter(actions:StudioAction[],path:string,action:StudioAction):boolean{const container=actionContainerAtPath(actions,path);if(!container)return false;container.list.splice(container.index+1,0,action);return true}
export function appendActionInside(actions:StudioAction[],path:string,action:StudioAction):boolean{const parent=actionAtPath(actions,path);if(!parent?.children)return false;parent.children.push(action);return true}
