export type StudioLocale='es'|'en';

const EN:Record<string,string>={
  'Preview web local':'Local web preview','Nuevo':'New','Abrir':'Open','Guardar':'Save','Exportar Lua':'Export Lua','Deshacer':'Undo','Rehacer':'Redo','Buscar':'Search','Comandos':'Commands','Comprobar API':'Check API','Proyectos':'Projects','Inspector':'Inspector','Local':'Local',
  'Mapa':'Map','Editor':'Editor','Problemas':'Issues','Mapas locales':'Local maps','Configuración':'Settings','Duplicar':'Duplicate','Eliminar':'Delete','Activadores':'Triggers','Convertir Lua a activadores':'Convert Lua to triggers','Cerrar':'Close','Cancelar':'Cancel','Convertir':'Convert','Buscar en el proyecto':'Search project','Paleta de comandos':'Command palette','Plantillas locales de activadores':'Local trigger templates',
  'Nivel del editor':'Editor level','Básico':'Basic','Intermedio':'Intermediate','Avanzado':'Advanced','Buscar bloques':'Search blocks','Acciones':'Actions','Mensaje':'Message','Esperar':'Wait','Condición Si':'If condition','Repetir':'Repeat','Variable':'Variable','Lua libre':'Free-form Lua','API Mini World':'Mini World API','CUANDO':'WHEN','SI':'IF','Sin condiciones iniciales':'No initial conditions','Añade o arrastra una acción desde la paleta.':'Add or drag an action from the palette.',
  'Favoritas':'Favorites','Recientes':'Recent','Todas las API':'All APIs','Copiar código':'Copy code','Descargar .lua':'Download .lua','Simular este activador':'Simulate this trigger','Ejecutar prueba local':'Run local test','Variables finales':'Final variables','Proyecto':'Project','Título':'Title','Descripción':'Description','Comportamiento':'Behavior','Seguridad':'Security','Analizar proyecto':'Analyze project','Restablecer posición del mapa':'Reset map position',
  'Subir':'Move up','Bajar':'Move down','Copiar':'Copy','Cortar':'Cut','Pegar después':'Paste after','Pegar dentro':'Paste inside','Otro valor o variable…':'Other value or variable…','Sí':'Yes','No':'No','Jugador del evento':'Event player','Jugador o actor objetivo':'Target player or actor','Actor seleccionado':'Selected actor','Ningún jugador (nil)':'No player (nil)','Todos':'All','Muertos':'Dead','Vivos':'Alive'
};
Object.assign(EN,{
  'Idioma':'Language','Guardado local':'Saved locally','Encajar':'Fit','Mover mapa':'Move map','Mover activadores':'Move triggers','Sin acciones':'No actions','Nombre del activador':'Trigger name','Evento':'Event','Datos del evento:':'Event data:','ninguno documentado':'none documented','Nombre de función':'Function name','Incluir al exportar':'Include in export','Condiciones':'Conditions','Variables':'Variables','Duplicar activador':'Duplicate trigger','Importar Lua':'Import Lua','Guardar plantilla':'Save template','Plantillas locales':'Local templates',
  'Cuando inicia el juego':'When the game starts','Cuando termina el juego':'When the game ends','Cuando entra un jugador':'When a player joins','Cuando sale un jugador':'When a player leaves','Cuando muere un jugador':'When a player dies','Cuando revive un jugador':'When a player revives','Cuando sube de nivel':'When a player levels up','Cuando cambia acceso rápido':'When the quick slot changes','Cuando obtiene un objeto':'When an item is obtained','Cuando consume un objeto':'When an item is consumed','Cuando colocan un bloque':'When a block is placed','Cuando destruyen un bloque':'When a block is destroyed','Cuando se retira un bloque':'When a block is removed','Cuando se activa un bloque':'When a block is activated','Cuando se crea un actor':'When an actor is created','Cuando muere un actor':'When an actor dies','Cuando cambia un atributo':'When an attribute changes','Cuando un actor entra en un área':'When an actor enters an area','Cuando se crea un objeto':'When an item is created','Cuando recogen un objeto':'When an item is picked up','Cuando se crea un proyectil':'When a projectile is created','Cuando un proyectil entra en un área':'When a projectile enters an area','Cuando se pulsa un botón':'When a button is pressed','Cuando aparece una interfaz':'When a UI appears','Cuando se oculta una interfaz':'When a UI is hidden','Cuando un campo pierde el foco':'When a field loses focus','Cuando cambia un temporizador':'When a timer changes','Cuando termina una receta':'When a recipe finishes'
});

Object.assign(EN,{'Arrastra el fondo o la cabecera azul del activador.':'Drag the background or the trigger blue header.'});
export function translateText(text:string,locale:StudioLocale):string{if(locale==='en')return EN[text]||text;const spanish=Object.fromEntries(Object.entries(EN).map(([es,en])=>[en,es]));return spanish[text]||text}
export function applyTranslations(root:HTMLElement,locale:StudioLocale):void{
  root.lang=locale;
  const dictionary=locale==='en'?EN:Object.fromEntries(Object.entries(EN).map(([es,en])=>[en,es]));
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;
  while((node=walker.nextNode())){const parent=node.parentElement;if(!parent||parent.closest('pre,code,textarea,[data-code]'))continue;const raw=node.nodeValue||'',trimmed=raw.trim(),translated=dictionary[trimmed];if(translated)node.nodeValue=raw.replace(trimmed,translated)}
  root.querySelectorAll<HTMLElement>('[title],[placeholder],[aria-label]').forEach(element=>{for(const attr of ['title','placeholder','aria-label']){const value=element.getAttribute(attr);if(value&&dictionary[value])element.setAttribute(attr,dictionary[value])}});
}
