export type StudioLocale='es'|'en';

const EN:Record<string,string>={
  'Preview web local':'Local web preview','Nuevo':'New','Abrir':'Open','Guardar':'Save','Exportar Lua':'Export Lua','Deshacer':'Undo','Rehacer':'Redo','Buscar':'Search','Comandos':'Commands','Comprobar API':'Check API','Proyectos':'Projects','Inspector':'Inspector','Local':'Local',
  'Mapa':'Map','Editor':'Editor','Problemas':'Issues','Mapas locales':'Local maps','Configuración':'Settings','Duplicar':'Duplicate','Eliminar':'Delete','Activadores':'Triggers','Convertir Lua a activadores':'Convert Lua to triggers','Cerrar':'Close','Cancelar':'Cancel','Convertir':'Convert','Buscar en el proyecto':'Search project','Paleta de comandos':'Command palette','Plantillas locales de activadores':'Local trigger templates',
  'Nivel del editor':'Editor level','Básico':'Basic','Intermedio':'Intermediate','Avanzado':'Advanced','Buscar bloques':'Search blocks','Acciones':'Actions','Mensaje':'Message','Esperar':'Wait','Condición Si':'If condition','Repetir':'Repeat','Variable':'Variable','Lua libre':'Free-form Lua','API Mini World':'Mini World API','CUANDO':'WHEN','SI':'IF','Sin condiciones iniciales':'No initial conditions','Añade o arrastra una acción desde la paleta.':'Add or drag an action from the palette.',
  'Favoritas':'Favorites','Recientes':'Recent','Todas las API':'All APIs','Copiar código':'Copy code','Descargar .lua':'Download .lua','Simular este activador':'Simulate this trigger','Ejecutar prueba local':'Run local test','Variables finales':'Final variables','Proyecto':'Project','Título':'Title','Descripción':'Description','Comportamiento':'Behavior','Seguridad':'Security','Analizar proyecto':'Analyze project','Restablecer posición del mapa':'Reset map position',
  'Subir':'Move up','Bajar':'Move down','Copiar':'Copy','Cortar':'Cut','Pegar después':'Paste after','Pegar dentro':'Paste inside','Otro valor o variable…':'Other value or variable…','Sí':'Yes','No':'No','Jugador del evento':'Event player','Jugador o actor objetivo':'Target player or actor','Actor seleccionado':'Selected actor','Ningún jugador (nil)':'No player (nil)','Todos':'All','Muertos':'Dead','Vivos':'Alive'
};
Object.assign(EN,{
  'Atajos':'Shortcuts','Atajos de teclado':'Keyboard shortcuts','Atajos de teclado (Ctrl+/)':'Keyboard shortcuts (Ctrl+/)','Mostrar atajos de teclado':'Show keyboard shortcuts','Ayuda':'Help',
  'Guardando…':'Saving…','Error al guardar localmente':'Local save failed','Reintentar guardado':'Retry save',
  'Respaldo del espacio de trabajo':'Workspace backup','Incluye proyectos, preferencias y plantillas locales. Los puntos de recuperación no se incluyen para mantener el archivo pequeño.':'Includes projects, preferences, and local templates. Recovery points are excluded to keep the file small.','Crear respaldo':'Create backup','Restaurar respaldo':'Restore backup','La restauración añade copias y nunca reemplaza los proyectos actuales.':'Restoring adds copies and never replaces current projects.','Respaldo del espacio de trabajo creado':'Workspace backup created','No se pudo crear el respaldo.':'Could not create the backup.','No se pudo restaurar el respaldo.':'Could not restore the backup.',
  'Idioma':'Language','Guardado local':'Saved locally','Encajar':'Fit','Mover mapa':'Move map','Mover activadores':'Move triggers','Sin acciones':'No actions','Nombre del activador':'Trigger name','Evento':'Event','Datos del evento:':'Event data:','ninguno documentado':'none documented','Nombre de función':'Function name','Incluir al exportar':'Include in export','Condiciones':'Conditions','Variables':'Variables','Duplicar activador':'Duplicate trigger','Importar Lua':'Import Lua','Guardar plantilla':'Save template','Plantillas locales':'Local templates',
  'Cuando inicia el juego':'When the game starts','Cuando termina el juego':'When the game ends','Cuando entra un jugador':'When a player joins','Cuando sale un jugador':'When a player leaves','Cuando muere un jugador':'When a player dies','Cuando revive un jugador':'When a player revives','Cuando sube de nivel':'When a player levels up','Cuando cambia acceso rápido':'When the quick slot changes','Cuando obtiene un objeto':'When an item is obtained','Cuando consume un objeto':'When an item is consumed','Cuando colocan un bloque':'When a block is placed','Cuando destruyen un bloque':'When a block is destroyed','Cuando se retira un bloque':'When a block is removed','Cuando se activa un bloque':'When a block is activated','Cuando se crea un actor':'When an actor is created','Cuando muere un actor':'When an actor dies','Cuando cambia un atributo':'When an attribute changes','Cuando un actor entra en un área':'When an actor enters an area','Cuando se crea un objeto':'When an item is created','Cuando recogen un objeto':'When an item is picked up','Cuando se crea un proyectil':'When a projectile is created','Cuando un proyectil entra en un área':'When a projectile enters an area','Cuando se pulsa un botón':'When a button is pressed','Cuando aparece una interfaz':'When a UI appears','Cuando se oculta una interfaz':'When a UI is hidden','Cuando un campo pierde el foco':'When a field loses focus','Cuando cambia un temporizador':'When a timer changes','Cuando termina una receta':'When a recipe finishes'
});

Object.assign(EN,{'Arrastra el fondo o la cabecera azul del activador.':'Drag the background or the trigger blue header.'});
Object.assign(EN,{
  'Arrastrar bloque':'Drag block','Vida máxima':'Maximum health','Vida actual':'Current health','Recuperación de vida':'Health recovery','Número de vidas':'Number of lives','Hambre máxima':'Maximum hunger','Hambre actual':'Current hunger','Oxígeno máximo':'Maximum oxygen','Oxígeno actual':'Current oxygen','Recuperación de oxígeno':'Oxygen recovery','Velocidad al caminar':'Walking speed','Velocidad al correr':'Running speed','Velocidad agachado':'Crouching speed','Velocidad al nadar':'Swimming speed','Fuerza de salto':'Jump power','Evasión':'Dodge','Ataque cuerpo a cuerpo':'Melee attack','Ataque a distancia':'Ranged attack','Defensa cuerpo a cuerpo':'Melee defense','Defensa a distancia':'Ranged defense','Tamaño del modelo':'Model size','Puntuación':'Score','Nivel de estrellas':'Star level','Experiencia actual':'Current experience','Nivel actual':'Current level','Resistencia actual':'Current stamina','Resistencia máxima':'Maximum stamina','Recuperación de resistencia':'Stamina recovery',
  'Juego':'Game','Jugador':'Player','Inventario':'Inventory','Bloques':'Blocks','Objetos':'Items','Proyectiles':'Projectiles','Interfaz':'UI','Sistema':'System','Mundo':'World','Control':'Control',
  'mensaje':'message','jugador':'player','Jugador que originó el evento':'Player that triggered the event','atributo':'attribute','valor':'value','ID de objeto':'item ID','cantidad':'amount','prioridad':'priority','ID de música':'music ID','volumen':'volume','tono':'pitch','repetir':'repeat','ID de interfaz':'UI ID','efecto':'effect','duración':'duration','estado':'state','ID de criatura':'creature ID','jugador o nil':'player or nil','ID de proyectil':'projectile ID','dirección X':'X direction','dirección Y':'Y direction','dirección Z':'Z direction','velocidad':'speed','ID de actor':'actor ID','hora (0-24)':'hour (0-24)','ID de sonido':'sound ID','vida':'health','modelo':'model','ID de bloque':'block ID','datos':'data','soltar objetos':'drop items','cara':'face','color':'color','ID de elemento':'element ID','texto':'text','animación':'animation','color hexadecimal':'hex color','ID de textura':'texture ID','ancho':'width','alto':'height','tamaño':'size','grados':'degrees','transparencia':'opacity','escala X':'X scale','escala Y':'Y scale','ID de estado':'status ID','nombre del evento':'event name','segundos':'seconds','estado (-1 todos, 0 muertos, 1 vivos)':'state (-1 all, 0 dead, 1 alive)',
  'Mostrar mensaje del sistema':'Show system message','Mostrar {contenido} a {jugador}':'Show {contenido} to {jugador}','Enviar mensaje al chat':'Send chat message','Enviar {contenido} al chat de {jugador}':'Send {contenido} to {jugador} chat',
  'Obtener nombre del jugador':'Get player name','Obtener el nombre de {jugador}':'Get the name of {jugador}','Cambiar atributo del jugador':'Change player attribute','Cambiar {atributo} de {jugador} a {valor}':'Set {atributo} of {jugador} to {valor}','Obtener atributo del jugador':'Get player attribute','Obtener {atributo} de {jugador}':'Get {atributo} of {jugador}','Entregar objetos':'Give items','Entregar {cantidad} del objeto {itemid} a {jugador}':'Give {cantidad} of item {itemid} to {jugador}','Mover jugador':'Move player','Mover {jugador} a X {x}, Y {y}, Z {z}':'Move {jugador} to X {x}, Y {y}, Z {z}','Marcar victoria':'Set victory','Dar la victoria a {jugador}':'Give victory to {jugador}','Reproducir música':'Play music','Reproducir música {musicId} para {jugador} con volumen {volumen}':'Play music {musicId} for {jugador} at volume {volumen}','Detener música':'Stop music','Detener la música de {jugador}':'Stop music for {jugador}','Abrir interfaz':'Open UI','Abrir interfaz {uiid} en {jugador}':'Open UI {uiid} for {jugador}','Cerrar interfaz':'Close UI','Cerrar interfaz {uiid} en {jugador}':'Close UI {uiid} for {jugador}',
  'Obtener todos los jugadores':'Get all players','Obtener jugadores con estado {estado}':'Get players with state {estado}','Contar jugadores':'Count players','Contar los jugadores actuales':'Count current players','Crear criatura':'Spawn creature','Crear {cantidad} criatura(s) {actorid} en X {x}, Y {y}, Z {z}':'Spawn {cantidad} creature(s) {actorid} at X {x}, Y {y}, Z {z}','Crear objeto':'Spawn item','Crear {cantidad} del objeto {itemid} en X {x}, Y {y}, Z {z}':'Spawn {cantidad} of item {itemid} at X {x}, Y {y}, Z {z}','Crear proyectil por dirección':'Spawn directional projectile','Lanzar proyectil {itemid} desde X {x}, Y {y}, Z {z} hacia {dx}, {dy}, {dz}':'Launch projectile {itemid} from X {x}, Y {y}, Z {z} toward {dx}, {dy}, {dz}','Eliminar actor':'Remove actor','Eliminar el actor {objid}':'Remove actor {objid}','Cambiar hora':'Change time','Cambiar la hora del mundo a {hora}':'Set world time to {hora}','Reproducir sonido':'Play sound','Reproducir sonido {sonido} en X {x}, Y {y}, Z {z}':'Play sound {sonido} at X {x}, Y {y}, Z {z}',
  'Obtener posición de actor':'Get actor position','Obtener la posición del actor {objid}':'Get position of actor {objid}','Modificar vida':'Change health','Añadir {cantidad} de vida al actor {objid}':'Add {cantidad} health to actor {objid}','Cambiar modelo':'Change model','Cambiar el modelo de {objid} por {modelo}':'Change model of {objid} to {modelo}','Restaurar modelo':'Restore model','Restaurar el modelo inicial de {objid}':'Restore original model of {objid}','Eliminar al actor {objid}':'Remove actor {objid}','Mover actor a posición':'Move actor to position','Mover actor {objid} a X {x}, Y {y}, Z {z} con velocidad {velocidad}':'Move actor {objid} to X {x}, Y {y}, Z {z} at speed {velocidad}',
  'Obtener ID de bloque':'Get block ID','Obtener el bloque en X {x}, Y {y}, Z {z}':'Get block at X {x}, Y {y}, Z {z}','Colocar bloque':'Place block','Colocar bloque {blockid} en X {x}, Y {y}, Z {z}':'Place block {blockid} at X {x}, Y {y}, Z {z}','Destruir bloque':'Destroy block','Destruir bloque en X {x}, Y {y}, Z {z} y soltar objetos {soltar}':'Destroy block at X {x}, Y {y}, Z {z} and drop items {soltar}','Reemplazar bloque':'Replace block','Reemplazar por bloque {blockid} en X {x}, Y {y}, Z {z}':'Replace with block {blockid} at X {x}, Y {y}, Z {z}',
  'Añadir al inventario':'Add to inventory','Añadir {cantidad} del objeto {itemid} al inventario de {jugador}':'Add {cantidad} of item {itemid} to {jugador} inventory','Vaciar inventario':'Clear inventory','Vaciar todo el inventario de {jugador}':'Clear all inventory of {jugador}',
  'Cambiar texto de interfaz':'Change UI text','En {jugador}, establecer texto de {elementid} en interfaz {uiid} a {texto}':'For {jugador}, set {elementid} text in UI {uiid} to {texto}','Mostrar elemento':'Show element','Mostrar elemento {elementid} de interfaz {uiid} a {jugador}':'Show element {elementid} from UI {uiid} to {jugador}','Ocultar elemento':'Hide element','Ocultar elemento {elementid} de interfaz {uiid} a {jugador}':'Hide element {elementid} from UI {uiid} for {jugador}','Cambiar color':'Change color','Cambiar color de {elementid} en interfaz {uiid} para {jugador} a {color}':'Set color of {elementid} in UI {uiid} for {jugador} to {color}','Cambiar imagen o textura':'Change image or texture','Cambiar imagen de {elementid} en interfaz {uiid} para {jugador} a {textura}':'Set image of {elementid} in UI {uiid} for {jugador} to {textura}','Cambiar tamaño de elemento':'Resize element','Cambiar tamaño de {elementid} en interfaz {uiid} para {jugador} a ancho {ancho} y alto {alto}':'Resize {elementid} in UI {uiid} for {jugador} to width {ancho} and height {alto}','Cambiar tamaño de texto':'Change text size','Cambiar tamaño del texto de {elementid} a {tamano} para {jugador}':'Set text size of {elementid} to {tamano} for {jugador}','Girar elemento':'Rotate element','Girar {elementid} de interfaz {uiid} para {jugador} a {grados} grados':'Rotate {elementid} from UI {uiid} for {jugador} to {grados} degrees','Cambiar transparencia':'Change opacity','Cambiar transparencia de {elementid} en interfaz {uiid} para {jugador} a {alpha}':'Set opacity of {elementid} in UI {uiid} for {jugador} to {alpha}','Cambiar estado de interfaz':'Change UI state','Cambiar estado de interfaz {uiid} para {jugador} a {estado}':'Set UI {uiid} state for {jugador} to {estado}','Mover elemento de interfaz':'Move UI element','Mover {elementid} de interfaz {uiid} para {jugador} a X {x}, Y {y}':'Move {elementid} in UI {uiid} for {jugador} to X {x}, Y {y}','Escalar elemento':'Scale element','Escalar {elementid} de interfaz {uiid} para {jugador} a X {x}, Y {y}':'Scale {elementid} in UI {uiid} for {jugador} to X {x}, Y {y}',
  'Obtener icono de objeto':'Get item icon','Obtener icono del objeto {itemid}':'Get icon for item {itemid}','Obtener icono de criatura':'Get creature icon','Obtener icono de la criatura {objid}':'Get icon for creature {objid}','Obtener icono de tipo de criatura':'Get creature type icon','Obtener icono del tipo de criatura {actorid}':'Get icon for creature type {actorid}','Obtener icono de estado':'Get status icon','Obtener icono del estado {statusid}':'Get icon for status {statusid}','Obtener icono de bloque':'Get block icon','Obtener icono del bloque {blockid}':'Get icon for block {blockid}',
  'Terminar partida':'End game','Terminar la partida actual':'End the current game','Enviar evento personalizado':'Send custom event','Enviar evento {evento} con datos {datos}':'Send event {evento} with data {datos}','Esperar {segundos} segundos':'Wait {segundos} seconds'
});
Object.assign(EN,{
  'Añadir a favoritas':'Add to favorites','mensaje, mundo, jugador...':'message, world, player...',
  'Convertir Lua':'Convert Lua','Comprobación local, sin ejecutar Lua':'Local check without running Lua','No se detectaron patrones peligrosos.':'No dangerous patterns detected.','APIs detectadas:':'Detected APIs:','ninguna':'none',
  'Problemas del proyecto':'Project issues','Revisión completamente local; no ejecuta ni envía Lua.':'Fully local review; it does not run or send Lua.','Volver a analizar':'Analyze again','Errores':'Errors','Advertencias':'Warnings','Sugerencias':'Suggestions','Métricas estructurales':'Structural metrics','No predicen FPS ni latencia.':'They do not predict FPS or latency.','Copiar resumen':'Copy summary','Llamadas API':'API calls','Revisión manual':'Manual review','Complejidad baja':'Low complexity','Estructural':'Structural','API más usadas':'Most used APIs','Sin llamadas API.':'No API calls.','Por activador':'By trigger','Sugerencia':'Suggestion','Abrir activador':'Open trigger',
  'Mapas locales disponibles en la aplicación':'Local maps available in the app','El preview web no recibe acceso a AppData. Usa el instalador Tauri para probar el indexador; el resto del proyecto y las preferencias sí funcionan localmente aquí.':'The web preview cannot access AppData. Use the Tauri installer to test the indexer; the rest of the project and preferences work locally here.',
  'Lua global previo a los activadores':'Global Lua before triggers','Básico · solo opciones necesarias':'Basic · only required options','Intermedio · permite elegir API':'Intermediate · API selection enabled','Avanzado · Lua, resultados y argumentos':'Advanced · Lua, results and arguments','Mantener la pestaña al añadir un activador':'Keep the tab open after adding a trigger','Mostrar código en el mapa':'Show code on the map','Permitir mover el mapa':'Allow moving the map','Permitir mover activadores':'Allow moving triggers','Reemplazar llamadas por nombres fáciles':'Replace calls with friendly names','Mostrar cuadrícula':'Show grid','Máximo 2.5 MB. El Studio no ejecuta Lua. Los bloques no reconocidos se mantienen visibles como Lua libre.':'Maximum 2.5 MB. Studio does not run Lua. Unrecognized blocks remain visible as free-form Lua.','Recuperación':'Recovery','Cargando puntos locales…':'Loading local recovery points…','Máximo un punto automático por minuto, 20 por proyecto y 16 MB en total.':'At most one automatic point per minute, 20 per project and 16 MB total.','Se conserva como máximo un punto automático por minuto, 20 por proyecto y 16 MB por edición.':'At most one automatic point per minute, 20 per project and 16 MB per edition.','Crear punto ahora':'Create point now','Restaurar como copia':'Restore as copy','Eliminar puntos de este proyecto':'Delete this project’s recovery points','Todavía no hay puntos de recuperación.':'There are no recovery points yet.','No se pudo abrir el historial local.':'Could not open local recovery history.'
});
const EN_PATTERNS:Array<[RegExp,(match:RegExpMatchArray)=>string]>=[
  [/^(\d+) error\(es\)$/m,m=>`${m[1]} error(s)`],[/^Proyecto #(\d+) · (\d+) activador\(es\)$/m,m=>`Project #${m[1]} · ${m[2]} trigger(s)`],[/^(\d+) mapa\(s\) encontrado\(s\)$/m,m=>`${m[1]} map(s) found`],[/^(\d+) mapa\(s\)$/m,m=>`${m[1]} map(s)`],[/^(\d+) habilitados$/m,m=>`${m[1]} enabled`],[/^Profundidad (\d+)$/m,m=>`Depth ${m[1]}`],[/^(\d+) métodos$/m,m=>`${m[1]} methods`],[/^(\d+) variables$/m,m=>`${m[1]} variables`],[/^(\d+) acciones · profundidad (\d+) · complejidad (\d+)$/m,m=>`${m[1]} actions · depth ${m[2]} · complexity ${m[3]}`],[/^Análisis: (.+)$/m,m=>`Analysis: ${m[1]}`],[/^APIs detectadas: (.+)$/m,m=>`Detected APIs: ${m[1]}`],[/^(.+): está habilitado pero no contiene acciones\.$/m,m=>`${m[1]}: is enabled but contains no actions.`]
];
const ES_PATTERNS:Array<[RegExp,(match:RegExpMatchArray)=>string]>=[
  [/^(\d+) error\(s\)$/m,m=>`${m[1]} error(es)`],[/^Project #(\d+) · (\d+) trigger\(s\)$/m,m=>`Proyecto #${m[1]} · ${m[2]} activador(es)`],[/^(\d+) map\(s\) found$/m,m=>`${m[1]} mapa(s) encontrado(s)`],[/^(\d+) map\(s\)$/m,m=>`${m[1]} mapa(s)`],[/^(\d+) enabled$/m,m=>`${m[1]} habilitados`],[/^Depth (\d+)$/m,m=>`Profundidad ${m[1]}`],[/^(\d+) methods$/m,m=>`${m[1]} métodos`],[/^(\d+) variables$/m,m=>`${m[1]} variables`],[/^(\d+) actions · depth (\d+) · complexity (\d+)$/m,m=>`${m[1]} acciones · profundidad ${m[2]} · complejidad ${m[3]}`],[/^Analysis: (.+)$/m,m=>`Análisis: ${m[1]}`],[/^Detected APIs: (.+)$/m,m=>`APIs detectadas: ${m[1]}`],[/^(.+): is enabled but contains no actions\.$/m,m=>`${m[1]}: está habilitado pero no contiene acciones.`]
];
export function translateText(text:string,locale:StudioLocale):string{const dictionary=locale==='en'?EN:Object.fromEntries(Object.entries(EN).map(([es,en])=>[en,es])),exact=dictionary[text];if(exact)return exact;for(const [pattern,render] of locale==='en'?EN_PATTERNS:ES_PATTERNS){const match=text.match(pattern);if(match)return render(match)}return text}
export function applyTranslations(root:HTMLElement,locale:StudioLocale):void{
  root.lang=locale;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null;
  while((node=walker.nextNode())){const parent=node.parentElement;if(!parent||parent.closest('pre,code,textarea,[data-code]'))continue;const raw=node.nodeValue||'',trimmed=raw.trim(),translated=translateText(trimmed,locale);if(translated!==trimmed)node.nodeValue=raw.replace(trimmed,translated)}
  root.querySelectorAll<HTMLElement>('[title],[placeholder],[aria-label]').forEach(element=>{for(const attr of ['title','placeholder','aria-label']){const value=element.getAttribute(attr);if(value){const translated=translateText(value,locale);if(translated!==value)element.setAttribute(attr,translated)}}});
}
