import './styles.css';
import './save-state.css';
import './shortcuts.css';
import './pointer-fix.css';
import './action-fields.css';
import './local-maps.css';
import './diagnostics.css';
import './recovery.css';
import './search.css';
import './trigger-templates.css';
import './metrics.css';
import './api-preferences.css';
import './command-palette.css';
import './panel-layout.css';
import './preview-mode.css';
import './variable-refactor.css';
import './editor-mode.css';
import './simulator.css';
import './nested-editor.css';
import { EVENTS, METHODS, eventById, methodByKey, methodDefaultTargets, splitLuaArguments } from './catalog';
import { EDITION_LABEL, HAS_NETWORK, checkRemote, openHomepage } from './edition';
import { analyzeProjectMetrics, cloneAction, cloneTrigger, createAction, createCondition, createProject, createTrigger, createVariable, generateLua, importLua, inspectProject, organizeMethodKeys, renameVariableReferences, scanLua, searchProject, validateProject, type ActionType, type StudioAction, type StudioProject, type StudioTrigger } from './studio-core';
import { clearRecoveryPoints, createRecoveryPoint, exportLua, exportProject, exportWorkspaceBackup, importProject, importWorkspaceBackup, listProjects, listRecoveryPoints, listTriggerTemplates, loadStudioPreferences, mergeWorkspaceTemplates, persistProjects, persistStudioPreferences, removeTriggerTemplate, saveTriggerTemplate, type StudioPreferences } from './persistence';
import { mergeWorkspaceProjects } from './workspace-backup';
import { scanLocalMaps, type LocalMapScan } from './local-maps';
import { filterStudioCommands, type StudioCommand } from './command-palette';
import { togglePanelLayout, type PanelTarget } from './panel-layout';
import { IS_TAURI_RUNTIME } from './platform-storage';
import { methodDefaultValueForContext, parameterPreset, valueSourceOptions } from './parameter-options';
import { simulateTrigger } from './simulator';
import { actionAtPath, appendActionInside, findActionPath, insertActionAfter, moveActionBefore, moveActionByOffset, moveActionToRootEnd, removeActionAtPath } from './action-tree';
import { applyTranslations, translateText } from './i18n';

const appElement = document.querySelector<HTMLDivElement>('#app');
if (!appElement) throw new Error('No se encontró #app');
const app: HTMLDivElement = appElement;

let projects: StudioProject[] = [], project = createProject(), activeTriggerId = project.triggers[0].id;
let actionClipboard:StudioAction|null=null;
let history: string[] = [], future: string[] = [], saveTimer = 0, draggedAction = '', mapDragging = false;
let saveQueue:Promise<boolean>=Promise.resolve(true);
let localMapScan:LocalMapScan|null=null;
let studioPreferences:StudioPreferences={favoriteMethods:[],recentMethods:[],projectPanelVisible:true,inspectorVisible:true,locale:'es'};

app.innerHTML = `
  <header class="app-bar">
    <strong>Mini World ID Studio</strong>${IS_TAURI_RUNTIME?'':'<strong class="preview-badge">Preview web local</strong>'}<button class="edition" data-home>${EDITION_LABEL}</button>
    <span class="separator"></span><button data-new>Nuevo</button><button data-import-project>Abrir</button><button data-save-file>Guardar</button><button data-export-lua>Exportar Lua</button>
    <span class="separator"></span><button data-undo>Deshacer</button><button data-redo>Rehacer</button><button data-search title="Buscar en el proyecto (Ctrl+K)">Buscar</button><button data-commands title="Paleta de comandos (Ctrl+Shift+P)">Comandos</button>${HAS_NETWORK ? '<button data-api>Comprobar API</button>' : ''}<span class="separator"></span><button class="panel-toggle" data-toggle-project-panel title="Mostrar u ocultar Proyectos (Ctrl+B)">Proyectos</button><button class="panel-toggle" data-toggle-inspector title="Mostrar u ocultar Inspector (Ctrl+Alt+I)">Inspector</button><span data-status data-save-state="idle">Local</span><button class="retry-save" data-retry-save hidden>Reintentar guardado</button>
  </header>
  <nav class="view-tabs" aria-label="Vistas del proyecto"><button data-view-tab="map">Mapa</button><button data-view-tab="editor">Editor</button><button data-view-tab="lua">Lua</button><button data-view-tab="diagnostics">Problemas</button><button data-view-tab="localmaps">Mapas locales</button><button data-view-tab="config">Configuración</button></nav>
  <main class="studio-shell">
    <aside class="project-panel"><div class="panel-title"><strong>Proyectos</strong><button data-add-project title="Nuevo proyecto">+</button></div><div data-projects class="project-list"></div><div class="project-commands"><button data-duplicate-project>Duplicar</button><button data-delete-project>Eliminar</button></div><div class="panel-title"><strong>Activadores</strong><button data-add-trigger title="Nuevo activador">+</button></div><div data-triggers class="trigger-list"></div></aside>
    <section class="workspace"><div data-workspace class="workspace-content"></div></section>
    <aside class="inspector"><div class="panel-title"><strong>Inspector</strong><span data-selection></span></div><div data-inspector></div></aside>
  </main>
  <dialog data-lua-dialog><form method="dialog"><header><strong>Convertir Lua a activadores</strong><button value="cancel" aria-label="Cerrar">×</button></header><p>El código reconocido se convierte en bloques. Las instrucciones desconocidas se conservan como Lua libre.</p><textarea data-lua-source spellcheck="false"></textarea><footer><button value="cancel">Cancelar</button><button value="default" data-convert-lua>Convertir</button></footer></form></dialog>
  <dialog class="search-dialog" data-search-dialog><div><header><strong>Buscar en el proyecto</strong><button type="button" data-close-search aria-label="Cerrar">×</button></header><input data-project-search placeholder="Activador, evento, variable, API…" autocomplete="off"><div data-search-results class="search-results"></div><footer><small>Ctrl+K para abrir · Enter para elegir el primer resultado</small></footer></div></dialog>
  <dialog class="command-dialog" data-command-dialog><div><header><strong>Paleta de comandos</strong><button type="button" data-close-commands aria-label="Cerrar">×</button></header><input data-command-search placeholder="Escribe una acción o vista…" autocomplete="off"><div data-command-results class="command-results"></div><footer><small>Ctrl+Shift+P o F1 · ↑ ↓ para navegar · Enter para ejecutar</small></footer></div></dialog>
  <dialog class="trigger-template-dialog" data-trigger-template-dialog><div><header><strong>Plantillas locales de activadores</strong><button type="button" data-close-trigger-templates aria-label="Cerrar">×</button></header><div data-trigger-template-list></div></div></dialog>`;

const query = <T extends Element>(selector: string): T => { const node = app.querySelector<T>(selector); if (!node) throw new Error(`Falta ${selector}`); return node; };
const shortcutButton=document.createElement('button');shortcutButton.dataset.shortcuts='';shortcutButton.title='Atajos de teclado (Ctrl+/)';shortcutButton.textContent='Atajos';query<HTMLButtonElement>('[data-commands]').after(shortcutButton);
const shortcutDialog=document.createElement('dialog');shortcutDialog.className='shortcut-dialog';shortcutDialog.dataset.shortcutDialog='';shortcutDialog.setAttribute('aria-labelledby','shortcut-dialog-title');shortcutDialog.innerHTML='<div><header><strong id="shortcut-dialog-title" data-shortcut-title>Atajos de teclado</strong><button type="button" data-close-shortcuts aria-label="Cerrar">×</button></header><p data-shortcut-intro></p><div data-shortcut-list></div></div>';app.append(shortcutDialog);
const languageLabel=document.createElement('label');languageLabel.className='language-picker';languageLabel.innerHTML='<span>Idioma</span><select data-language aria-label="Idioma / Language"><option value="es">Español</option><option value="en">English</option></select>';query<HTMLElement>('[data-status]').before(languageLabel);
const html = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character] || character);
const snap = (): string => JSON.stringify(project);
const nextProjectId = (): number => Math.max(0, ...projects.map((item) => item.id)) + 1;
const activeTrigger = (): StudioTrigger => project.triggers.find((item) => item.id === activeTriggerId) || project.triggers[0];
const setSaveState=(state:'idle'|'saving'|'saved'|'error',message:string,error?:unknown):void=>{const target=query<HTMLElement>('[data-status]'),retry=query<HTMLButtonElement>('[data-retry-save]');target.dataset.saveState=state;target.textContent=translateText(message,studioPreferences.locale);retry.hidden=state!=='error';target.title=error instanceof Error?error.message:''};
const status = (message: string): void => { const target=query<HTMLElement>('[data-status]');if(target.dataset.saveState==='error')return;target.textContent = translateText(message,studioPreferences.locale); };
const rememberMethod=(key:string):void=>{studioPreferences.recentMethods=[key,...studioPreferences.recentMethods.filter(item=>item!==key)].slice(0,20);void persistStudioPreferences(studioPreferences)};
const toggleFavoriteMethod=(key:string):void=>{studioPreferences.favoriteMethods=studioPreferences.favoriteMethods.includes(key)?studioPreferences.favoriteMethods.filter(item=>item!==key):[key,...studioPreferences.favoriteMethods].slice(0,50);void persistStudioPreferences(studioPreferences)};
const applyPanelLayout=():void=>{app.classList.toggle('project-panel-hidden',!studioPreferences.projectPanelVisible);app.classList.toggle('inspector-hidden',!studioPreferences.inspectorVisible);const left=app.querySelector<HTMLButtonElement>('[data-toggle-project-panel]'),right=app.querySelector<HTMLButtonElement>('[data-toggle-inspector]');left?.setAttribute('aria-pressed',String(studioPreferences.projectPanelVisible));right?.setAttribute('aria-pressed',String(studioPreferences.inspectorVisible))};
const togglePanel=(target:PanelTarget):void=>{const next=togglePanelLayout(studioPreferences,target);studioPreferences={...studioPreferences,...next};applyPanelLayout();void persistStudioPreferences(studioPreferences);status(target==='focus'?(next.projectPanelVisible?'Paneles restaurados':'Modo enfoque activado'):'Diseño del Studio actualizado')};

function commandCatalog():StudioCommand[]{return[
  {id:'view-map',label:'Abrir mapa de activadores',group:'Vista',keywords:'lienzo escritorio'},
  {id:'view-editor',label:'Abrir editor visual',group:'Vista',keywords:'bloques scratch'},
  {id:'view-lua',label:'Abrir código Lua',group:'Vista',keywords:'script exportar'},
  {id:'view-diagnostics',label:'Abrir problemas y métricas',group:'Vista',keywords:'errores análisis salud'},
  {id:'view-localmaps',label:'Abrir mapas locales',group:'Vista',keywords:'indexar miniworddata'},
  {id:'view-config',label:'Abrir configuración',group:'Vista',keywords:'ajustes recuperación'},
  {id:'new-trigger',label:'Crear activador',group:'Proyecto',keywords:'trigger evento',shortcut:'Ctrl+Alt+T'},
  {id:'new-project',label:'Crear proyecto',group:'Proyecto',keywords:'nuevo'},
  {id:'duplicate-project',label:'Duplicar proyecto',group:'Proyecto',keywords:'copia fork'},
  {id:'save-project',label:'Guardar archivo de proyecto',group:'Archivo',keywords:'exportar mwstudio',shortcut:'Ctrl+S'},
  {id:'export-lua',label:'Exportar código Lua',group:'Archivo',keywords:'descargar script'},
  {id:'convert-lua',label:'Convertir Lua a activadores',group:'Archivo',keywords:'importar script bloques'},
  {id:'search-project',label:'Buscar en el proyecto',group:'Edición',keywords:'activador variable API',shortcut:'Ctrl+K'},
  {id:'undo',label:'Deshacer último cambio',group:'Edición',keywords:'revertir',shortcut:'Ctrl+Z',disabled:history.length===0},
  {id:'redo',label:'Rehacer cambio',group:'Edición',keywords:'repetir',shortcut:'Ctrl+Y',disabled:future.length===0},
  {id:'recovery',label:'Abrir puntos de recuperación',group:'Seguridad',keywords:'respaldo restaurar snapshot'},
  {id:'toggle-project-panel',label:`${studioPreferences.projectPanelVisible?'Ocultar':'Mostrar'} panel Proyectos`,group:'Diseño',keywords:'lateral izquierda',shortcut:'Ctrl+B'},
  {id:'toggle-inspector',label:`${studioPreferences.inspectorVisible?'Ocultar':'Mostrar'} Inspector`,group:'Diseño',keywords:'lateral derecha',shortcut:'Ctrl+Alt+I'},
  {id:'focus-mode',label:!studioPreferences.projectPanelVisible&&!studioPreferences.inspectorVisible?'Salir del modo enfoque':'Activar modo enfoque',group:'Diseño',keywords:'lienzo pantalla espacio',shortcut:'Ctrl+Shift+F'},
  {id:'show-shortcuts',label:'Mostrar atajos de teclado',group:'Ayuda',keywords:'teclas ayuda accesibilidad',shortcut:'Ctrl+/'}
]}

function runCommand(id:string):void{const views:Record<string,StudioProject['activeView']>={'view-map':'map','view-editor':'editor','view-lua':'lua','view-diagnostics':'diagnostics','view-localmaps':'localmaps','view-config':'config'};if(views[id]){switchView(views[id]);return;}const selectors:Record<string,string>={'new-trigger':'[data-add-trigger]','new-project':'[data-new]','duplicate-project':'[data-duplicate-project]','save-project':'[data-save-file]','export-lua':'[data-export-lua]','undo':'[data-undo]','redo':'[data-redo]'};if(selectors[id]){app.querySelector<HTMLButtonElement>(selectors[id])?.click();return;}if(id==='toggle-project-panel'){togglePanel('project');return;}if(id==='toggle-inspector'){togglePanel('inspector');return;}if(id==='focus-mode'){togglePanel('focus');return;}if(id==='show-shortcuts'){showKeyboardShortcuts();return;}if(id==='search-project'){showProjectSearch();return;}if(id==='convert-lua'){query<HTMLDialogElement>('[data-lua-dialog]').showModal();return;}if(id==='recovery'){switchView('config');window.setTimeout(()=>app.querySelector<HTMLElement>('[data-recovery-section]')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}}

function showCommandPalette():void{const dialog=query<HTMLDialogElement>('[data-command-dialog]'),input=query<HTMLInputElement>('[data-command-search]'),results=query<HTMLElement>('[data-command-results]');const paint=():void=>{const commands=filterStudioCommands(commandCatalog(),input.value);results.innerHTML=commands.length?commands.map(command=>`<button data-command-id="${html(command.id)}" ${command.disabled?'disabled':''}><span>${html(command.group)}</span><strong>${html(command.label)}</strong>${command.shortcut?`<kbd>${html(command.shortcut)}</kbd>`:'<i></i>'}</button>`).join(''):'<p>No se encontró ese comando.</p>';results.querySelectorAll<HTMLButtonElement>('[data-command-id]').forEach(button=>button.onclick=()=>{if(button.disabled)return;const id=String(button.dataset.commandId);dialog.close();runCommand(id)})};input.value='';paint();if(!dialog.open)dialog.showModal();window.setTimeout(()=>input.focus(),0);input.oninput=paint;input.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();results.querySelector<HTMLButtonElement>('[data-command-id]:not(:disabled)')?.click()}else if(event.key==='ArrowDown'){event.preventDefault();results.querySelector<HTMLButtonElement>('[data-command-id]:not(:disabled)')?.focus()}};query<HTMLButtonElement>('[data-close-commands]').onclick=()=>dialog.close();results.onkeydown=event=>{const buttons=Array.from(results.querySelectorAll<HTMLButtonElement>('[data-command-id]:not(:disabled)')),index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(event.key==='ArrowDown'){event.preventDefault();buttons[Math.min(buttons.length-1,index+1)]?.focus()}else if(event.key==='ArrowUp'){event.preventDefault();if(index<=0)input.focus();else buttons[index-1]?.focus()}else if(event.key==='Enter'&&index>=0){event.preventDefault();buttons[index].click()}}}

function showKeyboardShortcuts():void{const dialog=query<HTMLDialogElement>('[data-shortcut-dialog]'),english=studioPreferences.locale==='en',items=[['Ctrl+K','Buscar en el proyecto','Search the project'],['Ctrl+Shift+P / F1','Paleta de comandos','Command palette'],['Ctrl+S','Guardar archivo de proyecto','Save project file'],['Ctrl+Z','Deshacer cambio','Undo change'],['Ctrl+Y','Rehacer cambio','Redo change'],['Ctrl+Alt+T','Crear activador','Create trigger'],['Ctrl+B','Mostrar u ocultar Proyectos','Toggle Projects'],['Ctrl+Alt+I','Mostrar u ocultar Inspector','Toggle Inspector'],['Ctrl+Shift+F','Activar modo enfoque','Toggle focus mode'],['Ctrl+/','Mostrar esta guía','Show this guide']];query<HTMLElement>('[data-shortcut-title]').textContent=english?'Keyboard shortcuts':'Atajos de teclado';query<HTMLElement>('[data-shortcut-intro]').textContent=english?'Shortcuts do not run while you are typing in a text field.':'Los atajos no se ejecutan mientras escribes en un campo de texto.';query<HTMLElement>('[data-shortcut-list]').innerHTML=`<dl>${items.map(item=>`<div><dt><kbd>${html(item[0])}</kbd></dt><dd>${html(english?item[2]:item[1])}</dd></div>`).join('')}</dl>`;query<HTMLButtonElement>('[data-close-shortcuts]').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();query<HTMLButtonElement>('[data-close-shortcuts]').focus()}

function showProjectSearch():void{const dialog=query<HTMLDialogElement>('[data-search-dialog]'),input=query<HTMLInputElement>('[data-project-search]'),results=query<HTMLElement>('[data-search-results]');const paint=():void=>{const matches=searchProject(project,input.value);results.innerHTML=input.value.trim()?matches.length?matches.map((match,index)=>`<button data-search-result="${index}"><span>${html(match.kind)}</span><strong>${html(match.title)}</strong><small>${html(match.detail)}</small></button>`).join(''):'<p>No se encontraron resultados.</p>':'<p>Escribe para buscar en todo el proyecto.</p>';results.querySelectorAll<HTMLButtonElement>('[data-search-result]').forEach(button=>button.onclick=()=>{const match=matches[Number(button.dataset.searchResult)];if(!match)return;activeTriggerId=match.triggerId;dialog.close();project.activeView='editor';render();void saveAll();status(`${match.kind} abierto desde la búsqueda`)})};input.value='';paint();if(!dialog.open)dialog.showModal();window.setTimeout(()=>input.focus(),0);input.oninput=paint;input.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();results.querySelector<HTMLButtonElement>('[data-search-result]')?.click()}};query<HTMLButtonElement>('[data-close-search]').onclick=()=>dialog.close()}

async function showTriggerTemplates():Promise<void>{const dialog=query<HTMLDialogElement>('[data-trigger-template-dialog]'),list=query<HTMLElement>('[data-trigger-template-list]');if(!dialog.open)dialog.showModal();list.innerHTML='<p>Cargando plantillas…</p>';query<HTMLButtonElement>('[data-close-trigger-templates]').onclick=()=>dialog.close();try{const templates=await listTriggerTemplates();list.innerHTML=templates.length?`<div class="trigger-template-list">${templates.map(template=>`<article><div><strong>${html(template.name)}</strong><small>${html(eventById(template.trigger.event)?.name||template.trigger.event)} · ${template.trigger.actions.length} acción(es)</small></div><button data-use-trigger-template="${html(template.id)}">Añadir</button><button class="danger-button" data-remove-trigger-template="${html(template.id)}">Eliminar</button></article>`).join('')}</div>`:'<p class="empty-panel">Guarda un activador desde el Inspector para reutilizarlo aquí.</p>';list.querySelectorAll<HTMLButtonElement>('[data-use-trigger-template]').forEach(button=>button.onclick=()=>{const template=templates.find(item=>item.id===button.dataset.useTriggerTemplate);if(!template)return;const before=snap(),copy=cloneTrigger(template.trigger,project.triggers.length+1);copy.name=template.name;project.triggers.push(copy);activeTriggerId=copy.id;dialog.close();project.activeView='editor';commit(before,'Activador añadido desde plantilla')});list.querySelectorAll<HTMLButtonElement>('[data-remove-trigger-template]').forEach(button=>button.onclick=async()=>{const template=templates.find(item=>item.id===button.dataset.removeTriggerTemplate);if(!template||!confirm(`¿Eliminar la plantilla local “${template.name}”?`))return;await removeTriggerTemplate(template.id);status('Plantilla local eliminada');await showTriggerTemplates()})}catch(error){list.innerHTML=`<p>${html(error instanceof Error?error.message:'No se pudieron abrir las plantillas locales.')}</p>`}}

function saveAll(): Promise<boolean> {
  setSaveState('saving','Guardando…');
  saveQueue=saveQueue.then(async()=>{setSaveState('saving','Guardando…');try{const index=projects.findIndex(item=>item.id===project.id);if(index>=0)projects[index]=project;else projects.unshift(project);await persistProjects(projects);setSaveState('saved','Guardado local');return true}catch(error){setSaveState('error','Error al guardar localmente',error);return false}});
  return saveQueue;
}

function commit(previous: string, message = 'Cambio guardado', shouldRender = true): void {
  if (previous !== snap()) { history.push(previous); history = history.slice(-150); future = []; void createRecoveryPoint(JSON.parse(previous) as StudioProject, message); }
  project.updatedAt = new Date().toISOString();
  window.clearTimeout(saveTimer); saveTimer = window.setTimeout(() => void saveAll(), 220);
  if (shouldRender) render(); status(message);
}

function switchView(view: StudioProject['activeView']): void { project.activeView = view; render(); void saveAll(); }

function renderProjects(): void {
  query<HTMLElement>('[data-projects]').innerHTML = projects.map((item) => `<button data-project-id="${item.id}" class="${item.id === project.id ? 'active' : ''}"><strong>${html(item.title)}</strong><small>Proyecto #${item.id} · ${item.triggers.length} activador(es)</small></button>`).join('');
  app.querySelectorAll<HTMLButtonElement>('[data-project-id]').forEach((button) => button.onclick = () => { const found = projects.find((item) => item.id === Number(button.dataset.projectId)); if (!found) return; project = found; activeTriggerId = project.triggers[0]?.id || ''; history = []; future = []; render(); });
}

function renderTriggers(): void {
  query<HTMLElement>('[data-triggers]').innerHTML = project.triggers.map((trigger, index) => `<article class="trigger-row ${trigger.id === activeTriggerId ? 'active' : ''} ${trigger.enabled ? '' : 'disabled'}" draggable="true" data-trigger-row="${trigger.id}"><span>${index + 1}</span><button data-trigger-id="${trigger.id}"><strong>${html(trigger.name)}</strong><small>${html(eventById(trigger.event)?.name || trigger.event)}</small></button><button data-remove-trigger="${trigger.id}" title="Eliminar">×</button></article>`).join('');
  app.querySelectorAll<HTMLButtonElement>('[data-trigger-id]').forEach((button) => button.onclick = () => { activeTriggerId = String(button.dataset.triggerId); render(); });
  app.querySelectorAll<HTMLButtonElement>('[data-remove-trigger]').forEach((button) => button.onclick = () => removeTrigger(String(button.dataset.removeTrigger)));
  let dragged = '';
  app.querySelectorAll<HTMLElement>('[data-trigger-row]').forEach((row) => { row.ondragstart = () => { dragged = String(row.dataset.triggerRow); }; row.ondragover = (event) => event.preventDefault(); row.ondrop = () => { const from = project.triggers.findIndex((item) => item.id === dragged), to = project.triggers.findIndex((item) => item.id === row.dataset.triggerRow); if (from < 0 || to < 0 || from === to) return; const before = snap(), [item] = project.triggers.splice(from, 1); project.triggers.splice(to, 0, item); commit(before, 'Activadores reordenados'); }; });
}

function eventOptions(selected: string): string {
  const groups = new Map<string, typeof EVENTS>(); EVENTS.forEach((entry) => groups.set(entry.group, [...(groups.get(entry.group) || []), entry]));
  return Array.from(groups).map(([group, entries]) => `<optgroup label="${html(group)}">${entries.map((entry) => `<option value="${html(entry.id)}" ${entry.id === selected ? 'selected' : ''}>${html(entry.name)}</option>`).join('')}</optgroup>`).join('');
}

function renderMap(host: HTMLElement): void {
  const zoom = Math.min(1.8, Math.max(.45, project.settings.zoom));
  host.innerHTML = `<div class="workspace-tools"><button data-zoom-out>−</button><strong>${Math.round(zoom * 100)}%</strong><button data-zoom-in>+</button><button data-fit>Encajar</button><label class="check"><input data-free-move type="checkbox" ${project.settings.freeMapMovement ? 'checked' : ''}> Mover mapa</label><label class="check"><input data-move-triggers type="checkbox" ${project.settings.moveTriggers ? 'checked' : ''}> Mover activadores</label><span>Arrastra el fondo o la cabecera azul del activador.</span></div><div class="map-viewport ${project.settings.grid ? '' : 'no-grid'}" data-map><div class="map-world" data-map-world style="transform:translate(${project.settings.mapX}px,${project.settings.mapY}px) scale(${zoom})">${project.triggers.map((trigger) => { const actions = trigger.actions.slice(0, 6).map((action) => `<span class="flow-block ${action.type}">${html(action.label)}</span>`).join('') || '<span class="flow-block empty">Sin acciones</span>'; const preview = project.settings.showCodeOnMap ? `<pre>${html(generateLua({ ...project, preamble: '', triggers: [trigger] }).split('\n').slice(2, 11).join('\n'))}</pre>` : ''; return `<article class="trigger-card ${trigger.id === activeTriggerId ? 'active' : ''} ${trigger.enabled ? '' : 'disabled'}" data-map-trigger="${trigger.id}" style="left:${trigger.x}px;top:${trigger.y}px"><button class="event-block">${html(trigger.name)}<small>${html(eventById(trigger.event)?.name || trigger.event)}</small></button><div class="trigger-flow">${actions}${preview}</div></article>`; }).join('')}</div></div>`;
  const map = host.querySelector<HTMLElement>('[data-map]'), world = host.querySelector<HTMLElement>('[data-map-world]'); if (!map || !world) return;
  const applyTransform = (): void => { world.style.transform = `translate(${project.settings.mapX}px,${project.settings.mapY}px) scale(${project.settings.zoom})`; };
  const updateZoom = (nextZoom: number): void => {
    const before = snap();
    project.settings.zoom = Math.min(1.8, Math.max(.45, nextZoom));
    applyTransform();
    const zoomLabel = host.querySelector<HTMLElement>('.workspace-tools strong');
    if (zoomLabel) zoomLabel.textContent = `${Math.round(project.settings.zoom * 100)}%`;
    commit(before, 'Zoom actualizado', false);
  };
  map.onwheel = (event) => { event.preventDefault(); updateZoom(project.settings.zoom + (event.deltaY < 0 ? .1 : -.1)); };
  let mapPointerId: number | null = null, mapBefore = '', mapLastX = 0, mapLastY = 0, mapOriginX = 0, mapOriginY = 0, mapDragBounds: DOMRect | null = null;
  map.onpointerdown = (event) => {
    if (!project.settings.freeMapMovement || (event.target as Element).closest('[data-map-trigger]') || (event.pointerType === 'mouse' && event.button !== 0)) return;
    event.preventDefault();
    mapDragging = true; mapPointerId = event.pointerId; mapBefore = snap(); mapLastX = event.clientX; mapLastY = event.clientY; mapOriginX = project.settings.mapX; mapOriginY = project.settings.mapY; mapDragBounds = map.getBoundingClientRect();
    map.setPointerCapture(event.pointerId);
  };
  map.onpointermove = (event) => {
    if (!mapDragging || event.pointerId !== mapPointerId || !Number.isFinite(event.clientX) || !Number.isFinite(event.clientY)) return;
    if (event.pointerType === 'mouse' && (event.buttons & 1) === 0) return;
    if (mapDragBounds && (event.clientX < mapDragBounds.left || event.clientX > mapDragBounds.right || event.clientY < mapDragBounds.top || event.clientY > mapDragBounds.bottom)) return;
    const stepX=event.clientX-mapLastX,stepY=event.clientY-mapLastY;
    if(Math.abs(stepX)>180||Math.abs(stepY)>180||(event.clientX===0&&event.clientY===0))return;
    project.settings.mapX += stepX; project.settings.mapY += stepY; mapLastX=event.clientX; mapLastY=event.clientY;
    applyTransform();
  };
  const finishMapDrag = (event: PointerEvent, cancelled: boolean): void => {
    if (event.pointerId !== mapPointerId) return;
    if (map.hasPointerCapture(event.pointerId)) map.releasePointerCapture(event.pointerId);
    mapDragging = false; mapPointerId = null; mapDragBounds = null;
    if (cancelled) { project.settings.mapX = mapOriginX; project.settings.mapY = mapOriginY; applyTransform(); return; }
    if(mapBefore!==snap()){history.push(mapBefore);history=history.slice(-150);future=[];project.updatedAt=new Date().toISOString();void saveAll();status('Mapa desplazado sin alterar activadores');}
  };
  map.onpointerup = (event) => finishMapDrag(event, false);
  map.onpointercancel = (event) => finishMapDrag(event, true);
  host.querySelectorAll<HTMLElement>('[data-map-trigger]').forEach((card) => {
    const trigger = project.triggers.find((item) => item.id === card.dataset.mapTrigger);
    const handle = card.querySelector<HTMLButtonElement>('.event-block');
    if (!trigger || !handle) return;
    let before = '', downX = 0, downY = 0, lastX = 0, lastY = 0, originX = 0, originY = 0, moved = false, suppressClick = false, dragging = false;
    handle.onclick = (event) => {
      if (suppressClick) { event.preventDefault(); suppressClick = false; return; }
      activeTriggerId = trigger.id;
      host.querySelectorAll<HTMLElement>('[data-map-trigger]').forEach((item)=>item.classList.toggle('active',item.dataset.mapTrigger===trigger.id));
      query<HTMLElement>('[data-triggers]').querySelectorAll<HTMLElement>('[data-trigger-row]').forEach((item)=>item.classList.toggle('active',item.dataset.triggerRow===trigger.id));
      renderInspector();
    };
    if (!project.settings.moveTriggers) return;
    handle.onmousedown = (event) => {
      if (event.button !== 0 || !Number.isFinite(event.clientX) || !Number.isFinite(event.clientY) || (event.clientX === 0 && event.clientY === 0)) return;
      event.preventDefault(); event.stopPropagation();
      before = snap(); downX = lastX = event.clientX; downY = lastY = event.clientY; originX = trigger.x; originY = trigger.y; moved = false; dragging = true;
      window.addEventListener('mousemove', moveTrigger, true);
      window.addEventListener('mouseup', finishTrigger, true);
      window.addEventListener('blur', finishTrigger, true);
    };
    const moveTrigger = (event: MouseEvent): void => {
      if (!dragging || !Number.isFinite(event.clientX) || !Number.isFinite(event.clientY) || (event.clientX === 0 && event.clientY === 0)) return;
      if ((event.buttons & 1) === 0) { finishTrigger(); return; }
      const bounds=map.getBoundingClientRect();if(event.clientX<bounds.left-80||event.clientX>bounds.right+80||event.clientY<bounds.top-80||event.clientY>bounds.bottom+80)return;
      if(Math.abs(event.clientX-lastX)>120||Math.abs(event.clientY-lastY)>120)return;
      const deltaX = event.clientX - downX, deltaY = event.clientY - downY;
      if (!moved && Math.hypot(event.clientX-downX,event.clientY-downY) < 3) return;
      event.preventDefault(); event.stopPropagation();
      moved = true;
      lastX=event.clientX;lastY=event.clientY;
      trigger.x = Math.max(0, originX + deltaX / zoom);
      trigger.y = Math.max(0, originY + deltaY / zoom);
      card.style.left = `${trigger.x}px`; card.style.top = `${trigger.y}px`;
    };
    const finishTrigger = (event?: MouseEvent | Event): void => {
      if (!dragging) return;
      event?.preventDefault(); event?.stopPropagation();
      dragging = false;
      window.removeEventListener('mousemove', moveTrigger, true);
      window.removeEventListener('mouseup', finishTrigger, true);
      window.removeEventListener('blur', finishTrigger, true);
      if (!moved) return;
      suppressClick = true;
      if (before !== snap()) { history.push(before); history = history.slice(-150); future = []; }
      project.updatedAt = new Date().toISOString();
      window.clearTimeout(saveTimer);
      void saveAll();
      status(`Activador guardado en X ${Math.round(trigger.x)}, Y ${Math.round(trigger.y)}`);
    };
  });
  host.querySelector<HTMLButtonElement>('[data-zoom-in]')!.onclick = () => updateZoom(project.settings.zoom + .1);
  host.querySelector<HTMLButtonElement>('[data-zoom-out]')!.onclick = () => updateZoom(project.settings.zoom - .1);
  host.querySelector<HTMLButtonElement>('[data-fit]')!.onclick = () => { const before = snap(); project.settings.zoom = 1; project.settings.mapX = 0; project.settings.mapY = 0; commit(before, 'Mapa centrado'); };
  host.querySelector<HTMLInputElement>('[data-free-move]')!.onchange = (event) => { const before = snap(); project.settings.freeMapMovement = (event.currentTarget as HTMLInputElement).checked; commit(before); };
  host.querySelector<HTMLInputElement>('[data-move-triggers]')!.onchange = (event) => { const before = snap(); project.settings.moveTriggers = (event.currentTarget as HTMLInputElement).checked; commit(before); };
}

function renderAction(action: StudioAction, path: string): string {
  const index=path;
  const editorMode=project.settings.editorMode;
  const parameterContext={eventFields:eventById(activeTrigger().event)?.fields||[],variables:activeTrigger().variables};
  const method = action.type === 'api' ? methodByKey(action.method || '') : undefined;
  const args = splitLuaArguments(action.value);
  const localizedPhrase=method?translateText(method.phrase,studioPreferences.locale):'';
  const phrase = method ? localizedPhrase.replace(/\{([^}]+)\}/g, (_, key: string) => { const paramIndex=method.params.findIndex(param=>param.key===key),param=method.params[paramIndex];if(!param)return`[${html(key)}]`;const value=args[paramIndex]||param.defaultValue,list=param.key.toLowerCase().includes('uiid')?' list="local-ui-ids"':param.key.toLowerCase().includes('elementid')?' list="local-element-ids"':' list="studio-value-sources"',preset=editorMode==='advanced'?undefined:parameterPreset(method.key,param,parameterContext);let control=`<input data-action-param="${index}" data-param-index="${paramIndex}" value="${html(value)}" spellcheck="false"${list}>`;if(preset){const known=preset.options.some(option=>option.value===value),custom=preset.allowCustom&&!known;control=`<select data-action-param-choice="${index}" data-param-index="${paramIndex}">${preset.options.map(option=>`<option value="${html(option.value)}" ${option.value===value?'selected':''}>${html(option.label)}</option>`).join('')}${preset.allowCustom?`<option value="__custom__" ${custom?'selected':''}>Otro valor o variable…</option>`:''}</select>${preset.allowCustom?`<input class="custom-param" data-action-param="${index}" data-param-index="${paramIndex}" value="${html(value)}" spellcheck="false" list="studio-value-sources" ${custom?'':'hidden'}>`:''}`};return`<label class="inline-param" title="${html(param.hint||param.label)}"><span>${html(param.label)}${param.optional?' (opcional)':''}</span>${control}</label>`; }) : '';
  const resultHint = method?.results.length ? `Sugeridos: ${method.results.join(', ')}` : 'Esta acción no necesita guardar resultados';
  const basicDetails: Record<Exclude<ActionType, 'api'>, string> = {
    message: `<div class="action-sentence">Mostrar mensaje <label class="inline-param"><span>texto</span><input data-action-value="${index}" value="${html(action.value)}"></label></div>`,
    wait: `<div class="action-sentence">Esperar <label class="inline-param"><span>segundos</span><input data-action-value="${index}" type="number" min="0" step="0.1" value="${html(action.value)}"></label> segundos</div>`,
    if: `<div class="action-sentence">Si <label class="inline-param"><span>condición Lua</span><input data-action-condition="${index}" value="${html(action.condition || action.value)}" spellcheck="false"></label> entonces</div>`,
    repeat: `<div class="action-sentence">Repetir <label class="inline-param"><span>veces</span><input data-action-value="${index}" type="number" min="1" max="1000" value="${html(action.value)}"></label> veces</div>`,
    set_variable: `<div class="action-sentence">Establecer <label class="inline-param"><span>asignación</span><input data-action-value="${index}" value="${html(action.value)}" spellcheck="false"></label></div>`,
    raw: editorMode==='advanced'?`<label class="raw-action-field">Código Lua libre<textarea data-action-value="${index}" spellcheck="false">${html(action.value)}</textarea></label>`:`<div class="advanced-only"><strong>Bloque Lua libre</strong><p>Cambia el editor a Avanzado para modificarlo.</p><pre>${html(action.value)}</pre></div>`,
  };
  const methodSelector=`<select data-action-method="${index}">${METHODS.map((entry) => `<option value="${entry.key}" ${entry.key === action.method ? 'selected' : ''}>${html(translateText(entry.name,studioPreferences.locale))} · ${entry.key}</option>`).join('')}</select>`,advancedApi=`<label class="action-result">Resultados Lua<input data-action-targets="${index}" value="${html(action.targets || '')}" placeholder="${html(resultHint)}"><small>${html(resultHint)}</small></label><details class="advanced-arguments"><summary>Argumentos Lua avanzados</summary><textarea data-action-value="${index}" placeholder="Argumentos separados por coma">${html(action.value)}</textarea></details>`;
  const details = method ? `${editorMode==='basic'?'':methodSelector}<div class="action-sentence">${phrase}</div>${editorMode==='advanced'?advancedApi:''}` : action.type === 'api' ? `${editorMode==='basic'?'<p class="advanced-only">Método no reconocido. Usa modo Intermedio o Avanzado para elegir otro.</p>':methodSelector}${editorMode==='advanced'?`<textarea data-action-value="${index}">${html(action.value)}</textarea>`:''}` : basicDetails[action.type];
  const children=action.children?`<div class="nested-actions" data-action-container="${html(path)}">${action.children.map((child,childIndex)=>renderAction(child,`${path}.${childIndex}`)).join('')||'<p class="empty-nested">Sin acciones internas.</p>'}<div class="nested-add"><select data-child-type="${html(path)}"><option value="message">Mensaje</option><option value="api">Llamada API</option><option value="wait">Esperar</option><option value="set_variable">Variable</option><option value="if">Condición Si</option><option value="repeat">Repetir</option>${editorMode==='advanced'?'<option value="raw">Lua libre</option>':''}</select><button data-add-child="${html(path)}">+ acción interna</button></div></div>`:'';
  const menu=`<details class="action-clipboard-menu"><summary title="Más acciones">⋯</summary><div><button data-duplicate-action="${html(path)}">Duplicar</button><button data-copy-action="${html(path)}">Copiar</button><button data-cut-action="${html(path)}">Cortar</button><button data-paste-after="${html(path)}" ${actionClipboard?'':'disabled'}>Pegar después</button>${action.children?`<button data-paste-inside="${html(path)}" ${actionClipboard?'':'disabled'}>Pegar dentro</button>`:''}</div></details>`;
  const displayLabel=method&&action.label===method.name?translateText(method.name,studioPreferences.locale):action.label;
  return `<article class="action-block ${action.type}" draggable="true" data-action-path="${html(path)}"><header><span class="drag-handle" title="Arrastrar bloque">⠿</span>${editorMode==='basic'?`<strong>${html(displayLabel)}</strong>`:`<input data-action-label="${html(path)}" value="${html(action.label)}">`}<button data-action-up="${html(path)}" title="Subir">↑</button><button data-action-down="${html(path)}" title="Bajar">↓</button><button data-remove-action="${html(path)}" title="Eliminar">×</button>${menu}</header>${details}${children}</article>`;
}

function renderEditor(host: HTMLElement): void {
  const trigger = activeTrigger();
  const valueSources=valueSourceOptions({eventFields:eventById(trigger.event)?.fields||[],variables:trigger.variables});
  host.innerHTML = `<div class="editor-shell" data-editor-mode="${project.settings.editorMode}"><aside class="block-palette"><label class="editor-mode-picker">Nivel del editor<select data-editor-mode-quick><option value="basic" ${project.settings.editorMode==='basic'?'selected':''}>Básico</option><option value="intermediate" ${project.settings.editorMode==='intermediate'?'selected':''}>Intermedio</option><option value="advanced" ${project.settings.editorMode==='advanced'?'selected':''}>Avanzado</option></select></label><label>Buscar bloques<input data-palette-search placeholder="mensaje, mundo, jugador..."></label><section data-basic-palette><strong>Acciones</strong><button data-new-action="message">Mensaje</button><button data-new-action="wait">Esperar</button><button data-new-action="if">Condición Si</button><button data-new-action="repeat">Repetir</button><button data-new-action="set_variable">Variable</button>${project.settings.editorMode==='advanced'?'<button data-new-action="raw">Lua libre</button>':''}</section><section class="api-palette"><strong>API Mini World</strong><div data-api-palette>${METHODS.map((method) => `<button data-api-method="${method.key}" data-search="${html(`${method.name} ${method.key} ${method.group}`.toLowerCase())}"><span>${html(method.name)}</span><small>${html(method.key)}</small></button>`).join('')}</div></section></aside><div class="block-editor"><div class="editor-event"><span>CUANDO</span><strong>${html(eventById(trigger.event)?.name || trigger.event)}</strong></div><div class="condition-summary">${trigger.conditions.length ? trigger.conditions.map((condition) => `<span>SI ${html(condition.field)} ${condition.operator} ${html(condition.value)}</span>`).join('') : '<span>Sin condiciones iniciales</span>'}</div><div class="action-stack" data-action-stack>${trigger.actions.map((action,index)=>renderAction(action,String(index))).join('') || '<div class="empty-editor">Añade o arrastra una acción desde la paleta.</div>'}</div></div></div>`;
  host.querySelector<HTMLElement>('.block-editor')?.insertAdjacentHTML('beforeend',simulatorMarkup(trigger));
  host.querySelector<HTMLSelectElement>('[data-editor-mode-quick]')!.onchange=event=>{const before=snap();project.settings.editorMode=(event.currentTarget as HTMLSelectElement).value as typeof project.settings.editorMode;commit(before,'Nivel del editor actualizado')};
  const uiIds=Array.from(new Set(project.localMap?.uiReferences.map(item=>item.uiId)||[]));const elementIds=Array.from(new Set(project.localMap?.uiReferences.flatMap(item=>item.elementId?[item.elementId]:[])||[]));host.insertAdjacentHTML('afterbegin',`<datalist id="local-ui-ids">${uiIds.map(id=>`<option value="${html(id)}"></option>`).join('')}</datalist><datalist id="local-element-ids">${elementIds.map(id=>`<option value="${html(id)}"></option>`).join('')}</datalist>${project.localMap?`<div class="local-map-context">Mapa local ${html(project.localMap.mapId)} · ${uiIds.length} UI</div>`:''}`);
  host.insertAdjacentHTML('afterbegin',`<datalist id="studio-value-sources">${valueSources.map(option=>`<option value="${html(option.value)}">${html(option.label)}</option>`).join('')}</datalist>`);
  const apiRoot=host.querySelector<HTMLElement>('[data-api-palette]');if(apiRoot){const buttons=new Map(Array.from(apiRoot.querySelectorAll<HTMLButtonElement>('[data-api-method]')).map(button=>[String(button.dataset.apiMethod),button])),organized=organizeMethodKeys(METHODS.map(method=>method.key),studioPreferences.favoriteMethods,studioPreferences.recentMethods);apiRoot.innerHTML='';const addGroup=(label:string,keys:string[]):void=>{if(!keys.length)return;const group=document.createElement('div');group.className='api-method-group';group.innerHTML=`<strong>${html(label)}</strong>`;keys.forEach(key=>{const button=buttons.get(key);if(!button)return;const row=document.createElement('div');row.className='api-method-row';row.dataset.apiRow='';row.dataset.search=String(button.dataset.search||'');const favorite=document.createElement('button');favorite.type='button';favorite.className='favorite-method';favorite.dataset.favoriteMethod=key;favorite.title=studioPreferences.favoriteMethods.includes(key)?'Quitar de favoritas':'Añadir a favoritas';favorite.setAttribute('aria-label',favorite.title);favorite.textContent=studioPreferences.favoriteMethods.includes(key)?'★':'☆';row.append(button,favorite);group.append(row)});apiRoot.append(group)};addGroup('Favoritas',organized.favorites);addGroup('Recientes',organized.recent);addGroup('Todas las API',organized.rest)}
  host.querySelectorAll<HTMLButtonElement>('[data-new-action]').forEach((button) => button.onclick = () => addAction(button.dataset.newAction as ActionType));
  host.querySelectorAll<HTMLButtonElement>('[data-api-method]').forEach((button) => { button.draggable = true; button.onclick = () => {const key=String(button.dataset.apiMethod);rememberMethod(key);addAction('api',key)}; button.ondragstart = (event) => {const key=String(button.dataset.apiMethod);rememberMethod(key);event.dataTransfer?.setData('application/x-mw-method',key)}; });
  host.querySelectorAll<HTMLButtonElement>('[data-favorite-method]').forEach(button=>button.onclick=()=>{toggleFavoriteMethod(String(button.dataset.favoriteMethod));renderEditor(host)});
  const search = host.querySelector<HTMLInputElement>('[data-palette-search]'); if (search) search.oninput = () => host.querySelectorAll<HTMLElement>('[data-api-row]').forEach((row) => row.hidden = !String(row.dataset.search).includes(search.value.trim().toLowerCase()));
  host.querySelectorAll<HTMLElement>('[data-action-path]').forEach(block=>{block.ondragstart=event=>{if(!(event.target as HTMLElement).closest('.drag-handle')){event.preventDefault();return}draggedAction=String(block.dataset.actionPath);event.stopPropagation();event.dataTransfer?.setData('application/x-mw-action',draggedAction)};block.ondragover=event=>{event.preventDefault();event.stopPropagation()};block.ondrop=event=>{event.preventDefault();event.stopPropagation();const method=event.dataTransfer?.getData('application/x-mw-method'),target=String(block.dataset.actionPath);if(method){const before=snap(),targetAction=actionAtPath(trigger.actions,target);if(targetAction?.children){const child=createAction('api'),entry=methodByKey(method);child.method=method;child.value=entry?methodDefaultValueForContext(entry,eventById(trigger.event)?.fields||[]):'';child.targets=entry?methodDefaultTargets(entry):'';child.label=project.settings.easyMode?entry?.name||method:method;targetAction.children.push(child);commit(before,'API añadida dentro del bloque')}else addAction('api',method);return}const source=event.dataTransfer?.getData('application/x-mw-action')||draggedAction;if(!source||source===target)return;const before=snap();if(moveActionBefore(trigger.actions,source,target))commit(before,'Bloque movido en el árbol')}});
  const stack=host.querySelector<HTMLElement>('[data-action-stack]');if(stack){stack.ondragover=event=>event.preventDefault();stack.ondrop=event=>{if((event.target as HTMLElement).closest('[data-action-path]'))return;const method=event.dataTransfer?.getData('application/x-mw-method');if(method){addAction('api',method);return}const source=event.dataTransfer?.getData('application/x-mw-action')||draggedAction;if(!source)return;const before=snap();if(moveActionToRootEnd(trigger.actions,source))commit(before,'Bloque movido al nivel principal')}}
  bindActionEditors(host, trigger);
  bindSimulator(host,trigger);
}

function simulatorMarkup(trigger:StudioTrigger):string{const fields=eventById(trigger.event)?.fields||[],payload=Object.fromEntries(fields.map(field=>[field,/^(?:x|y|z|level|itemnum|value)$/.test(field)?0:/content|name/i.test(field)?'':1]));return`<details class="trigger-simulator"><summary>Simular este activador</summary><p>Prueba el recorrido sin ejecutar Lua, esperar realmente ni enviar llamadas a Mini World.</p><label>Datos del evento (JSON)<textarea data-simulation-input spellcheck="false">${html(JSON.stringify(payload,null,2))}</textarea></label><div class="simulator-actions"><button data-run-simulation>Ejecutar prueba local</button><span>Máximo 250 pasos · 50 repeticiones</span></div><div data-simulation-result class="simulation-result"><p>Introduce los datos del evento y ejecuta la prueba.</p></div></details>`}
function bindSimulator(host:HTMLElement,trigger:StudioTrigger):void{const button=host.querySelector<HTMLButtonElement>('[data-run-simulation]'),input=host.querySelector<HTMLTextAreaElement>('[data-simulation-input]'),output=host.querySelector<HTMLElement>('[data-simulation-result]');if(!button||!input||!output)return;button.onclick=()=>{let payload:unknown;try{if(new Blob([input.value]).size>65_536)throw new Error('Los datos superan 64 KB.');payload=JSON.parse(input.value||'{}');if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Usa un objeto JSON con los campos del evento.')}catch(error){output.innerHTML=`<p class="simulation-error">${html(error instanceof Error?error.message:'JSON inválido.')}</p>`;return}const result=simulateTrigger(trigger,payload as Record<string,unknown>);output.innerHTML=`<header><strong>${result.passed?'Recorrido iniciado':'Activador omitido'}</strong><span>${result.apiCalls} API · ${result.warnings} avisos${result.halted?' · detenido por límite':''}</span></header><ol>${result.steps.map(step=>`<li class="simulation-${step.kind}" style="--simulation-depth:${Math.min(12,step.depth)}" ${step.actionId?`data-simulation-action="${html(step.actionId)}"`:''}><strong>${html(step.label)}</strong>${step.detail?`<small>${html(step.detail)}</small>`:''}</li>`).join('')}</ol><details><summary>Variables finales</summary><pre>${html(JSON.stringify(result.variables,null,2))}</pre></details>`;output.querySelectorAll<HTMLElement>('[data-simulation-action]').forEach(row=>row.onclick=()=>{const path=findActionPath(trigger.actions,String(row.dataset.simulationAction)),card=path?host.querySelector<HTMLElement>(`[data-action-path="${path}"]`):null;card?.scrollIntoView({behavior:'smooth',block:'center'});card?.classList.add('simulation-highlight');window.setTimeout(()=>card?.classList.remove('simulation-highlight'),1200)})}}

function bindActionEditors(host: HTMLElement, trigger: StudioTrigger): void {
  const resolve=(path:string|undefined):StudioAction|undefined=>path===undefined?undefined:actionAtPath(trigger.actions,path);
  const change = (selector: string, apply: (action: StudioAction, input: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement) => void): void => host.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(selector).forEach((input) => input.onchange = () => { const action=resolve(input.dataset.actionLabel ?? input.dataset.actionValue ?? input.dataset.actionTargets ?? input.dataset.actionMethod ?? input.dataset.actionCondition); if (!action) return; const before = snap(); apply(action, input); commit(before); });
  change('[data-action-label]', (action, input) => action.label = input.value); change('[data-action-value]', (action, input) => action.value = input.value); change('[data-action-targets]', (action, input) => action.targets = input.value); change('[data-action-method]', (action, input) => { const method = methodByKey(input.value); action.method = input.value; action.value = method ? methodDefaultValueForContext(method,eventById(trigger.event)?.fields||[]) : ''; action.targets = method ? methodDefaultTargets(method) : ''; if (project.settings.easyMode) action.label = method?.name || input.value; }); change('[data-action-condition]', (action, input) => { action.condition = input.value; action.value = input.value; });
  host.querySelectorAll<HTMLInputElement>('[data-action-param]').forEach(input=>input.onchange=()=>{const action=resolve(input.dataset.actionParam),method=action?methodByKey(action.method||''):undefined,paramIndex=Number(input.dataset.paramIndex);if(!action||!method||!Number.isInteger(paramIndex))return;const before=snap(),args=splitLuaArguments(action.value);while(args.length<method.params.length)args.push(method.params[args.length].defaultValue);args[paramIndex]=input.value.trim()||method.params[paramIndex].defaultValue;action.value=args.join(', ');commit(before,'Parámetro actualizado')});
  host.querySelectorAll<HTMLSelectElement>('[data-action-param-choice]').forEach(select=>select.onchange=()=>{const action=resolve(select.dataset.actionParamChoice),method=action?methodByKey(action.method||''):undefined,paramIndex=Number(select.dataset.paramIndex);if(!action||!method||!Number.isInteger(paramIndex))return;if(select.value==='__custom__'){const custom=select.parentElement?.querySelector<HTMLInputElement>('.custom-param');if(custom){custom.hidden=false;custom.focus();custom.select()}return}const before=snap(),args=splitLuaArguments(action.value);while(args.length<method.params.length)args.push(method.params[args.length].defaultValue);args[paramIndex]=select.value;action.value=args.join(', ');commit(before,'Opción del parámetro actualizada')});
  host.querySelectorAll<HTMLButtonElement>('[data-remove-action]').forEach(button=>button.onclick=()=>{const before=snap();if(removeActionAtPath(trigger.actions,String(button.dataset.removeAction)))commit(before,'Bloque eliminado')});
  host.querySelectorAll<HTMLButtonElement>('[data-action-up],[data-action-down]').forEach(button=>button.onclick=()=>{const path=String(button.dataset.actionUp??button.dataset.actionDown),delta=button.hasAttribute('data-action-up')?-1:1,before=snap();if(moveActionByOffset(trigger.actions,path,delta))commit(before,'Bloque movido')});
  host.querySelectorAll<HTMLButtonElement>('[data-add-child]').forEach(button=>button.onclick=()=>{const path=String(button.dataset.addChild),action=resolve(path),type=host.querySelector<HTMLSelectElement>(`[data-child-type="${path}"]`)?.value as ActionType|undefined;if(!action?.children||!type)return;const before=snap(),child=createAction(type);if(type==='api'){const method=METHODS[0];child.method=method.key;child.value=methodDefaultValueForContext(method,eventById(trigger.event)?.fields||[]);child.targets=methodDefaultTargets(method);child.label=method.name}action.children.push(child);commit(before,'Acción interna añadida')});
  const copied=():void=>{host.querySelectorAll<HTMLButtonElement>('[data-paste-after],[data-paste-inside]').forEach(button=>button.disabled=false);status('Bloque copiado al portapapeles interno')};
  host.querySelectorAll<HTMLButtonElement>('[data-copy-action]').forEach(button=>button.onclick=()=>{const action=resolve(button.dataset.copyAction);if(!action)return;actionClipboard=structuredClone(action);button.closest('details')?.removeAttribute('open');copied()});
  host.querySelectorAll<HTMLButtonElement>('[data-cut-action]').forEach(button=>button.onclick=()=>{const path=String(button.dataset.cutAction),action=resolve(path);if(!action)return;const before=snap();actionClipboard=structuredClone(action);if(removeActionAtPath(trigger.actions,path))commit(before,'Bloque cortado')});
  host.querySelectorAll<HTMLButtonElement>('[data-duplicate-action]').forEach(button=>button.onclick=()=>{const path=String(button.dataset.duplicateAction),action=resolve(path);if(!action)return;const before=snap();if(insertActionAfter(trigger.actions,path,cloneAction(action)))commit(before,'Bloque duplicado')});
  host.querySelectorAll<HTMLButtonElement>('[data-paste-after]').forEach(button=>button.onclick=()=>{if(!actionClipboard)return;const before=snap();if(insertActionAfter(trigger.actions,String(button.dataset.pasteAfter),cloneAction(actionClipboard)))commit(before,'Bloque pegado')});
  host.querySelectorAll<HTMLButtonElement>('[data-paste-inside]').forEach(button=>button.onclick=()=>{if(!actionClipboard)return;const before=snap();if(appendActionInside(trigger.actions,String(button.dataset.pasteInside),cloneAction(actionClipboard)))commit(before,'Bloque pegado dentro')});
}

function renderLua(host: HTMLElement): void {
  const lua = generateLua(project), result = scanLua(lua);
  host.innerHTML = `<div class="lua-workspace"><header><button data-copy-lua>Copiar código</button><button data-download-lua>Descargar .lua</button><button data-open-converter>Convertir Lua</button><span class="scan-${result.status}">Análisis: ${result.status}</span></header><pre data-code>${html(lua)}</pre><section class="console"><strong>Comprobación local, sin ejecutar Lua</strong><p>${result.blocked.join(', ') || result.warnings.join(', ') || 'No se detectaron patrones peligrosos.'}</p><small>APIs detectadas: ${html(result.calls.join(', ') || 'ninguna')}</small></section></div>`;
  host.querySelector<HTMLButtonElement>('[data-copy-lua]')!.onclick = async () => { await navigator.clipboard.writeText(lua); status('Lua copiado'); };
  host.querySelector<HTMLButtonElement>('[data-download-lua]')!.onclick = () => void exportLua(project, lua);
  host.querySelector<HTMLButtonElement>('[data-open-converter]')!.onclick = () => query<HTMLDialogElement>('[data-lua-dialog]').showModal();
}

function renderDiagnostics(host: HTMLElement): void {
  const issues=inspectProject(project),metrics=analyzeProjectMetrics(project),counts={error:0,warning:0,info:0};issues.forEach(issue=>counts[issue.severity]+=1);
  const canFixPositions=issues.some(issue=>issue.code==='trigger-overlap'),canFixArguments=issues.some(issue=>issue.code==='api-arguments-missing');
  host.innerHTML=`<section class="diagnostics-view"><header><div><h2>Problemas del proyecto</h2><p>Revisión completamente local; no ejecuta ni envía Lua.</p></div><button data-refresh-issues>Volver a analizar</button></header><div class="diagnostic-summary"><article class="issue-error"><strong>${counts.error}</strong><span>Errores</span></article><article class="issue-warning"><strong>${counts.warning}</strong><span>Advertencias</span></article><article class="issue-info"><strong>${counts.info}</strong><span>Sugerencias</span></article></div>${canFixPositions||canFixArguments?`<div class="diagnostic-fixes"><strong>Correcciones rápidas y reversibles</strong>${canFixPositions?'<button data-fix-overlaps>Separar activadores superpuestos</button>':''}${canFixArguments?'<button data-fix-api-values>Completar valores API faltantes</button>':''}<small>Puedes deshacerlas con Ctrl+Z.</small></div>`:''}<div class="issue-list">${issues.length?issues.map(issue=>`<article class="project-issue issue-${issue.severity}"><span class="issue-badge">${issue.severity==='error'?'Error':issue.severity==='warning'?'Advertencia':'Sugerencia'}</span><div><strong>${html(issue.code)}</strong><p>${html(issue.message)}</p></div>${issue.triggerId?`<button data-open-issue="${html(issue.triggerId)}">Abrir activador</button>`:''}</article>`).join(''):'<div class="diagnostic-clean"><strong>Proyecto listo</strong><p>No se encontraron problemas conocidos.</p></div>'}</div></section>`;
  const metricsPanel=document.createElement('section');metricsPanel.className='project-metrics';metricsPanel.innerHTML=`<header><div><h3>Métricas estructurales</h3><p>No predicen FPS ni latencia.</p></div><button data-copy-metrics>Copiar resumen</button></header><div class="metric-grid"><article><strong>${metrics.triggers}</strong><span>Activadores</span><small>${metrics.enabledTriggers} habilitados</small></article><article><strong>${metrics.actions}</strong><span>Acciones</span><small>Profundidad ${metrics.maxDepth}</small></article><article><strong>${metrics.apiCalls}</strong><span>Llamadas API</span><small>${metrics.methods.length} métodos</small></article><article><strong>${metrics.conditions}</strong><span>Condiciones</span><small>${metrics.variables} variables</small></article><article><strong>${metrics.rawBlocks}</strong><span>Lua libre</span><small>Revisión manual</small></article><article class="complexity-${metrics.complexityLevel}"><strong>${metrics.complexity}</strong><span>Complejidad ${metrics.complexityLevel}</span><small>Estructural</small></article></div><div class="metric-details"><div><h4>API más usadas</h4>${metrics.methods.length?`<ol>${metrics.methods.slice(0,8).map(method=>`<li><code>${html(method.name)}</code><span>${method.count}</span></li>`).join('')}</ol>`:'<p>Sin llamadas API.</p>'}</div><div><h4>Por activador</h4>${metrics.byTrigger.map(item=>`<button data-open-metric="${html(item.triggerId)}"><strong>${html(item.name)}</strong><span>${item.actions} acciones · profundidad ${item.maxDepth} · complejidad ${item.complexity}</span></button>`).join('')}</div></div>`;host.querySelector('.diagnostic-summary')?.insertAdjacentElement('afterend',metricsPanel);metricsPanel.querySelector<HTMLButtonElement>('[data-copy-metrics]')!.onclick=async()=>{const report={generated_at:new Date().toISOString(),summary:{triggers:metrics.triggers,enabled_triggers:metrics.enabledTriggers,actions:metrics.actions,api_calls:metrics.apiCalls,raw_blocks:metrics.rawBlocks,conditions:metrics.conditions,variables:metrics.variables,max_depth:metrics.maxDepth,complexity:metrics.complexity,complexity_level:metrics.complexityLevel},methods:metrics.methods,events:metrics.events};await navigator.clipboard.writeText(JSON.stringify(report,null,2));status('Resumen estructural copiado sin código Lua')};metricsPanel.querySelectorAll<HTMLButtonElement>('[data-open-metric]').forEach(button=>button.onclick=()=>{activeTriggerId=String(button.dataset.openMetric);project.activeView='editor';render();void saveAll();status('Activador abierto desde las métricas')});
  host.querySelector<HTMLButtonElement>('[data-refresh-issues]')!.onclick=()=>renderDiagnostics(host);
  host.querySelectorAll<HTMLButtonElement>('[data-open-issue]').forEach(button=>button.onclick=()=>{activeTriggerId=String(button.dataset.openIssue);project.activeView='editor';render();void saveAll();status('Activador del problema abierto')});
  host.querySelector<HTMLButtonElement>('[data-fix-overlaps]')?.addEventListener('click',()=>{const before=snap(),occupied=new Set<string>();project.triggers.forEach((trigger,index)=>{let key=`${Math.round(trigger.x)}:${Math.round(trigger.y)}`;if(occupied.has(key)){const fallback=createTrigger(index+1);trigger.x=fallback.x;trigger.y=fallback.y;key=`${Math.round(trigger.x)}:${Math.round(trigger.y)}`;while(occupied.has(key)){trigger.x+=40;trigger.y+=40;key=`${Math.round(trigger.x)}:${Math.round(trigger.y)}`}}occupied.add(key)});commit(before,'Activadores superpuestos separados')});
  host.querySelector<HTMLButtonElement>('[data-fix-api-values]')?.addEventListener('click',()=>{const before=snap();const repair=(actions:StudioAction[]):void=>actions.forEach(action=>{if(action.type==='api'){const method=methodByKey(action.method||'');if(method){const args=splitLuaArguments(action.value),required=method.params.filter(param=>!param.optional).length;while(args.length<required)args.push(method.params[args.length].defaultValue);action.value=args.join(', ')}}if(action.children?.length)repair(action.children)});project.triggers.forEach(trigger=>repair(trigger.actions));commit(before,'Valores API faltantes completados')});
}

async function renderLocalMaps(host:HTMLElement):Promise<void>{
  if(!IS_TAURI_RUNTIME){host.innerHTML='<section class="preview-notice"><h2>Mapas locales disponibles en la aplicación</h2><p>El preview web no recibe acceso a AppData. Usa el instalador Tauri para probar el indexador; el resto del proyecto y las preferencias sí funcionan localmente aquí.</p></section>';return;}
  host.innerHTML=`<section class="local-maps-view"><header><div><h2>Mapas locales de Mini World</h2><p>Escaneo manual, local y de solo lectura.</p></div><button data-scan>${localMapScan?'Volver a escanear':'Escanear mapas'}</button></header><div data-results>${localMapScan?'':'<div class="local-map-empty"><strong>Escaneo desactivado</strong><p>Sólo se revisan las carpetas conocidas y mapas w + ID numérico.</p></div>'}</div></section>`;const results=host.querySelector<HTMLElement>('[data-results]')!;
  const paint=()=>{if(!localMapScan)return;const roots=localMapScan.roots.map(root=>`<li class="${root.available?'available':''}"><strong>${html(root.dataVersion)}</strong><span>${root.available?`${root.mapCount} mapa(s)`:'No instalada'}</span></li>`).join('');const maps=localMapScan.maps.map(map=>{const linked=project.localMap?.mapId===map.mapId&&project.localMap.dataVersion===map.dataVersion;return `<article class="local-map-card ${linked?'linked':''}"><header><div><h3>Mapa ${html(map.mapId)}</h3><p>Datos ${html(map.dataVersion)}${map.gameVersion?` · juego ${html(map.gameVersion)}`:''}</p></div><button data-link="${html(map.mapId)}" data-version="${html(map.dataVersion)}">${linked?'Desvincular':'Usar en este proyecto'}</button></header><dl><div><dt>Escenas</dt><dd>${map.sceneNames.length}</dd></div><div><dt>Archivos UI</dt><dd>${map.customUiFiles}</dd></div><div><dt>IDs</dt><dd>${map.uiReferences.length}</dd></div></dl>${map.warnings.map(w=>`<p class="local-map-warning">${html(w)}</p>`).join('')}</article>`}).join('');results.innerHTML=`<p class="privacy-note">${html(localMapScan.privacy)}</p><ul class="scan-roots">${roots}</ul><div class="local-map-grid">${maps||'<p>No se encontraron mapas.</p>'}</div>`;results.querySelectorAll<HTMLButtonElement>('[data-link]').forEach(button=>button.onclick=()=>{const map=localMapScan?.maps.find(item=>item.mapId===button.dataset.link&&item.dataVersion===button.dataset.version);if(!map)return;const before=snap();if(project.localMap?.mapId===map.mapId&&project.localMap.dataVersion===map.dataVersion)project.localMap=undefined;else project.localMap={mapId:map.mapId,dataVersion:map.dataVersion,uiReferences:map.uiReferences.map(item=>({uiId:item.uiId,elementId:item.elementId}))};commit(before,project.localMap?'Mapa local vinculado':'Mapa local desvinculado')})};paint();host.querySelector<HTMLButtonElement>('[data-scan]')!.onclick=async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;button.textContent='Escaneando…';try{localMapScan=await scanLocalMaps();paint();status(`${localMapScan.maps.length} mapa(s) encontrado(s)`)}catch(error){results.innerHTML=`<p>${html(error instanceof Error?error.message:String(error))}</p>`}finally{button.disabled=false;button.textContent='Volver a escanear'}};
}

async function renderRecoverySection(host:HTMLElement):Promise<void>{
  host.querySelector('[data-recovery-section]')?.remove();const section=document.createElement('section');section.dataset.recoverySection='';section.innerHTML='<h2>Recuperación</h2><p>Cargando puntos locales…</p>';host.querySelector('.config-grid')?.append(section);const sourceProjectId=project.id;
  try{const points=await listRecoveryPoints(sourceProjectId);if(project.id!==sourceProjectId||!section.isConnected)return;section.innerHTML=`<h2>Recuperación</h2><p>Máximo un punto automático por minuto, 20 por proyecto y 16 MB en total.</p><button data-create-recovery>Crear punto ahora</button>${points.length?`<div class="recovery-list">${points.map(point=>`<article><div><strong>${html(new Date(point.at).toLocaleString())}</strong><small>${html(point.reason)}</small></div><button data-restore-recovery="${html(point.id)}">Restaurar como copia</button></article>`).join('')}</div><button class="danger-button" data-clear-recovery>Eliminar puntos de este proyecto</button>`:'<p class="empty-panel">Todavía no hay puntos de recuperación.</p>'}`;section.querySelector<HTMLButtonElement>('[data-create-recovery]')!.onclick=async()=>{await createRecoveryPoint(project,'Punto manual',true);status('Punto de recuperación creado');await renderRecoverySection(host)};section.querySelectorAll<HTMLButtonElement>('[data-restore-recovery]').forEach(button=>button.onclick=async()=>{const point=points.find(item=>item.id===button.dataset.restoreRecovery);if(!point)return;const copy=structuredClone(point.project);copy.id=nextProjectId();copy.title=`${copy.title} (recuperado)`;copy.createdAt=copy.updatedAt=new Date().toISOString();copy.activeView='map';projects.unshift(copy);project=copy;activeTriggerId=copy.triggers[0]?.id||'';history=[];future=[];await saveAll();render();status('Punto restaurado como proyecto nuevo')});section.querySelector<HTMLButtonElement>('[data-clear-recovery]')?.addEventListener('click',async()=>{if(!confirm('¿Eliminar únicamente los puntos de recuperación de este proyecto?'))return;await clearRecoveryPoints(sourceProjectId);status('Puntos de recuperación eliminados');await renderRecoverySection(host)})}catch(error){section.innerHTML=`<h2>Recuperación</h2><p>${html(error instanceof Error?error.message:'No se pudo abrir el historial local.')}</p>`}
  applyTranslations(section,studioPreferences.locale);
}


function renderWorkspaceBackupSection(host:HTMLElement):void{
  const section=document.createElement('section');section.className='workspace-backup';section.innerHTML='<h2>Respaldo del espacio de trabajo</h2><p>Incluye proyectos, preferencias y plantillas locales. Los puntos de recuperación no se incluyen para mantener el archivo pequeño.</p><div class="backup-actions"><button data-export-workspace>Crear respaldo</button><button data-import-workspace>Restaurar respaldo</button></div><p class="backup-safety">La restauración añade copias y nunca reemplaza los proyectos actuales.</p>';host.querySelector('.config-grid')?.append(section);
  section.querySelector<HTMLButtonElement>('[data-export-workspace]')!.onclick=async()=>{try{if(!await saveAll())return;if(await exportWorkspaceBackup(projects,studioPreferences))status('Respaldo del espacio de trabajo creado')}catch(error){alert(error instanceof Error?error.message:'No se pudo crear el respaldo.')}};
  section.querySelector<HTMLButtonElement>('[data-import-workspace]')!.onclick=async()=>{try{const backup=await importWorkspaceBackup();if(!backup)return;const question=studioPreferences.locale==='en'?`Add ${backup.projects.length} project(s), merge ${backup.templates.length} template(s), and restore preferences? Current projects will not be replaced.`:`¿Añadir ${backup.projects.length} proyecto(s), combinar ${backup.templates.length} plantilla(s) y restaurar preferencias? Los proyectos actuales no serán reemplazados.`;if(!confirm(question))return;const merged=mergeWorkspaceProjects(projects,backup.projects),templatesAdded=await mergeWorkspaceTemplates(backup.templates);projects=merged.projects;project=merged.imported[0];activeTriggerId=project.triggers[0]?.id||'';history=[];future=[];studioPreferences=backup.preferences;await persistStudioPreferences(studioPreferences);applyPanelLayout();await saveAll();render();status(studioPreferences.locale==='en'?`Backup restored: ${merged.imported.length} project(s), ${templatesAdded} new template(s)`:`Respaldo restaurado: ${merged.imported.length} proyecto(s), ${templatesAdded} plantilla(s) nueva(s)`)}catch(error){alert(error instanceof Error?error.message:'No se pudo restaurar el respaldo.')}};
  applyTranslations(section,studioPreferences.locale);
}

function renderConfig(host: HTMLElement): void {
  host.innerHTML = `<div class="config-grid"><section><h2>Proyecto</h2><label>Título<input data-project-title value="${html(project.title)}"></label><label>Descripción<textarea data-project-description>${html(project.description)}</textarea></label><label>Lua global previo a los activadores<textarea data-preamble spellcheck="false">${html(project.preamble)}</textarea></label></section><section><h2>Comportamiento</h2><label>Nivel del editor<select data-editor-mode-setting><option value="basic" ${project.settings.editorMode==='basic'?'selected':''}>Básico · solo opciones necesarias</option><option value="intermediate" ${project.settings.editorMode==='intermediate'?'selected':''}>Intermedio · permite elegir API</option><option value="advanced" ${project.settings.editorMode==='advanced'?'selected':''}>Avanzado · Lua, resultados y argumentos</option></select></label><label class="check"><input data-setting="keepTabOnAdd" type="checkbox" ${project.settings.keepTabOnAdd ? 'checked' : ''}> Mantener la pestaña al añadir un activador</label><label class="check"><input data-setting="showCodeOnMap" type="checkbox" ${project.settings.showCodeOnMap ? 'checked' : ''}> Mostrar código en el mapa</label><label class="check"><input data-setting="freeMapMovement" type="checkbox" ${project.settings.freeMapMovement ? 'checked' : ''}> Permitir mover el mapa</label><label class="check"><input data-setting="moveTriggers" type="checkbox" ${project.settings.moveTriggers ? 'checked' : ''}> Permitir mover activadores</label><label class="check"><input data-setting="easyMode" type="checkbox" ${project.settings.easyMode ? 'checked' : ''}> Reemplazar llamadas por nombres fáciles</label><label class="check"><input data-setting="grid" type="checkbox" ${project.settings.grid ? 'checked' : ''}> Mostrar cuadrícula</label><button data-reset-map>Restablecer posición del mapa</button></section><section><h2>Seguridad</h2><p>Máximo 2.5 MB. El Studio no ejecuta Lua. Los bloques no reconocidos se mantienen visibles como Lua libre.</p><button data-run-scan>Analizar proyecto</button><pre data-config-result></pre></section></div>`;
  const bind = (selector: string, apply: (value: string) => void) => { const input = host.querySelector<HTMLInputElement | HTMLTextAreaElement>(selector); if (input) input.onchange = () => { const before = snap(); apply(input.value); commit(before); }; };
  bind('[data-project-title]', (value) => project.title = value); bind('[data-project-description]', (value) => project.description = value); bind('[data-preamble]', (value) => project.preamble = value);
  host.querySelectorAll<HTMLInputElement>('[data-setting]').forEach((input) => input.onchange = () => { const before = snap(), key = input.dataset.setting as 'keepTabOnAdd' | 'showCodeOnMap' | 'freeMapMovement' | 'moveTriggers' | 'easyMode' | 'grid'; project.settings[key] = input.checked; commit(before); });
  host.querySelector<HTMLSelectElement>('[data-editor-mode-setting]')!.onchange=event=>{const before=snap();project.settings.editorMode=(event.currentTarget as HTMLSelectElement).value as typeof project.settings.editorMode;commit(before,'Nivel del editor actualizado')};
  host.querySelector<HTMLButtonElement>('[data-reset-map]')!.onclick = () => { const before = snap(); project.settings.mapX = 0; project.settings.mapY = 0; project.settings.zoom = 1; commit(before); };
  host.querySelector<HTMLButtonElement>('[data-run-scan]')!.onclick = () => { const result = scanLua(generateLua(project)); host.querySelector<HTMLElement>('[data-config-result]')!.textContent = JSON.stringify(result, null, 2); };
  renderWorkspaceBackupSection(host);
  void renderRecoverySection(host);
}

function renderInspector(): void {
  const trigger = activeTrigger(), host = query<HTMLElement>('[data-inspector]'); query<HTMLElement>('[data-selection]').textContent = trigger?.name || 'Proyecto';
  if (!trigger) { host.innerHTML = '<p class="empty-panel">No hay activadores.</p>'; return; }
  const event = eventById(trigger.event);
  host.innerHTML = `<label>Nombre del activador<input data-trigger-name value="${html(trigger.name)}"></label><label>Evento<select data-trigger-event>${eventOptions(trigger.event)}</select></label><p class="event-data"><strong>Datos del evento:</strong> ${html(event?.fields.map((field) => `e.${field}`).join(', ') || 'ninguno documentado')}</p><label>Nombre de función<input data-function-name value="${html(trigger.functionName)}"></label><label class="check"><input data-trigger-enabled type="checkbox" ${trigger.enabled ? 'checked' : ''}> Incluir al exportar</label><div class="inspector-heading"><strong>Condiciones</strong><button data-add-condition>+</button></div><div>${trigger.conditions.map((condition, index) => `<div class="condition-row"><input data-condition-field="${index}" value="${html(condition.field)}"><select data-condition-operator="${index}">${['==', '~=', '>', '>=', '<', '<='].map((op) => `<option ${condition.operator === op ? 'selected' : ''}>${op}</option>`).join('')}</select><input data-condition-value="${index}" value="${html(condition.value)}"><button data-remove-condition="${index}">×</button></div>`).join('')}</div><div class="inspector-heading"><strong>Variables</strong><button data-add-variable>+</button></div><div>${trigger.variables.map((variable, index) => `<div class="variable-row"><input data-variable-name="${index}" value="${html(variable.name)}" title="Renombrar actualiza sus referencias Lua"><select data-variable-scope="${index}" title="Alcance"><option value="local" ${variable.scope==='local'?'selected':''}>local</option><option value="global" ${variable.scope==='global'?'selected':''}>global</option></select><select data-variable-type="${index}"><option ${variable.valueType === 'number' ? 'selected' : ''}>number</option><option ${variable.valueType === 'string' ? 'selected' : ''}>string</option><option ${variable.valueType === 'boolean' ? 'selected' : ''}>boolean</option></select><input data-variable-value="${index}" value="${html(variable.value)}"><button data-remove-variable="${index}">×</button></div>`).join('')}</div><div class="inspector-actions"><button data-duplicate-trigger>Duplicar activador</button><button data-convert-here>Importar Lua</button><button data-save-trigger-template>Guardar plantilla</button><button data-use-trigger-template>Plantillas locales</button></div>`;
  const bind = (selector: string, apply: (value: string) => void) => { const input = host.querySelector<HTMLInputElement | HTMLSelectElement>(selector); if (input) input.onchange = () => { const before = snap(); apply(input.value); commit(before); }; };
  bind('[data-trigger-name]', (value) => trigger.name = value); bind('[data-trigger-event]', (value) => trigger.event = value); bind('[data-function-name]', (value) => trigger.functionName = value);
  host.querySelector<HTMLInputElement>('[data-trigger-enabled]')!.onchange = (event) => { const before = snap(); trigger.enabled = (event.currentTarget as HTMLInputElement).checked; commit(before); };
  host.querySelector<HTMLButtonElement>('[data-add-condition]')!.onclick = () => { const before = snap(); trigger.conditions.push(createCondition()); commit(before); };
  host.querySelector<HTMLButtonElement>('[data-add-variable]')!.onclick = () => { const before = snap(); trigger.variables.push(createVariable()); commit(before); };
  trigger.conditions.forEach((condition, index) => { bind(`[data-condition-field="${index}"]`, (value) => condition.field = value); bind(`[data-condition-operator="${index}"]`, (value) => condition.operator = value as typeof condition.operator); bind(`[data-condition-value="${index}"]`, (value) => condition.value = value); });
  trigger.variables.forEach((variable, index) => {const nameInput=host.querySelector<HTMLInputElement>(`[data-variable-name="${index}"]`);if(nameInput)nameInput.onchange=()=>{const before=snap(),result=renameVariableReferences(project,trigger.id,variable.id,nameInput.value);if(!result.ok){alert(result.error);render();return}commit(before,`Variable ${result.oldName} renombrada a ${result.newName} · ${result.references} referencia(s)`)};bind(`[data-variable-scope="${index}"]`,(value)=>variable.scope=value as typeof variable.scope);bind(`[data-variable-type="${index}"]`, (value) => variable.valueType = value as typeof variable.valueType); bind(`[data-variable-value="${index}"]`, (value) => variable.value = value); });
  host.querySelectorAll<HTMLButtonElement>('[data-remove-condition]').forEach((button) => button.onclick = () => { const before = snap(); trigger.conditions.splice(Number(button.dataset.removeCondition), 1); commit(before); });
  host.querySelectorAll<HTMLButtonElement>('[data-remove-variable]').forEach((button) => button.onclick = () => { const before = snap(); trigger.variables.splice(Number(button.dataset.removeVariable), 1); commit(before); });
  host.querySelector<HTMLButtonElement>('[data-duplicate-trigger]')!.onclick = () => { const before = snap(), copy = cloneTrigger(trigger,project.triggers.length + 1); project.triggers.push(copy); activeTriggerId = copy.id; commit(before); };
  host.querySelector<HTMLButtonElement>('[data-convert-here]')!.onclick = () => query<HTMLDialogElement>('[data-lua-dialog]').showModal();
  host.querySelector<HTMLButtonElement>('[data-save-trigger-template]')!.onclick = async () => { const name=prompt('Nombre de la plantilla local:',trigger.name);if(!name?.trim())return;await saveTriggerTemplate(trigger,name);status('Plantilla local guardada'); };
  host.querySelector<HTMLButtonElement>('[data-use-trigger-template]')!.onclick = () => void showTriggerTemplates();
}

function addAction(type: ActionType, method = ''): void { const before = snap(), action = createAction(type),trigger=activeTrigger(); if (type === 'api' && method) { const entry = methodByKey(method); action.method = method; action.value = entry ? methodDefaultValueForContext(entry,eventById(trigger.event)?.fields||[]) : ''; action.targets = entry ? methodDefaultTargets(entry) : ''; action.label = project.settings.easyMode ? entry?.name || method : method; } trigger.actions.push(action); commit(before, 'Acción añadida'); }
function removeTrigger(id: string): void { if (project.triggers.length <= 1) { alert('El proyecto necesita al menos un activador.'); return; } const before = snap(), index = project.triggers.findIndex((item) => item.id === id); if (index < 0) return; project.triggers.splice(index, 1); activeTriggerId = project.triggers[Math.max(0, index - 1)].id; commit(before, 'Activador eliminado'); }

function render(): void {
  renderProjects(); renderTriggers(); renderInspector();
  app.querySelectorAll<HTMLButtonElement>('[data-view-tab]').forEach((button) => button.setAttribute('aria-pressed', String(button.dataset.viewTab === project.activeView)));
  const host = query<HTMLElement>('[data-workspace]');
  if (project.activeView === 'map') renderMap(host); else if (project.activeView === 'editor') renderEditor(host); else if (project.activeView === 'lua') renderLua(host); else if(project.activeView==='diagnostics')renderDiagnostics(host);else if(project.activeView==='localmaps')void renderLocalMaps(host);else renderConfig(host);
  const errors = validateProject(project); if (errors.length) status(`${errors.length} error(es)`);
  applyTranslations(app,studioPreferences.locale);
}

app.querySelectorAll<HTMLButtonElement>('[data-view-tab]').forEach((button) => button.onclick = () => switchView(button.dataset.viewTab as StudioProject['activeView']));
query<HTMLButtonElement>('[data-retry-save]').onclick=()=>void saveAll();
query<HTMLButtonElement>('[data-shortcuts]').onclick=()=>showKeyboardShortcuts();
query<HTMLButtonElement>('[data-add-trigger]').onclick = () => { const before = snap(), trigger = createTrigger(project.triggers.length + 1); project.triggers.push(trigger); activeTriggerId = trigger.id; if (!project.settings.keepTabOnAdd) project.activeView = 'editor'; commit(before, 'Activador creado'); };
query<HTMLButtonElement>('[data-add-project]').onclick = query<HTMLButtonElement>('[data-new]').onclick = () => { project = createProject(nextProjectId()); projects.unshift(project); activeTriggerId = project.triggers[0].id; history = []; future = []; render(); void saveAll(); };
query<HTMLButtonElement>('[data-duplicate-project]').onclick = () => { const copy = structuredClone(project); copy.id = nextProjectId(); copy.title += ' copia'; copy.createdAt = copy.updatedAt = new Date().toISOString(); copy.triggers=project.triggers.map((trigger,index)=>cloneTrigger(trigger,index+1,{rename:false,offset:0})); projects.unshift(copy); project = copy; activeTriggerId = copy.triggers[0].id; history = []; future = []; render(); void saveAll(); };
query<HTMLButtonElement>('[data-delete-project]').onclick = async () => { if (!confirm(`¿Eliminar “${project.title}” del almacenamiento local?`)) return; await createRecoveryPoint(project,'Antes de eliminar el proyecto',true); projects = projects.filter((item) => item.id !== project.id); if (!projects.length) projects = [createProject(1)]; project = projects[0]; activeTriggerId = project.triggers[0].id; history = []; future = []; render(); void saveAll(); };
query<HTMLButtonElement>('[data-import-project]').onclick = async () => { try { const imported = await importProject(); if (!imported) return; if (projects.some((item) => item.id === imported.id)) imported.id = nextProjectId(); projects.unshift(imported); project = imported; activeTriggerId = project.triggers[0].id; history = []; future = []; render(); void saveAll(); } catch (error) { alert(error instanceof Error ? error.message : 'No se pudo abrir el proyecto.'); } };
query<HTMLButtonElement>('[data-save-file]').onclick = () => void exportProject(project); query<HTMLButtonElement>('[data-export-lua]').onclick = () => void exportLua(project, generateLua(project));
query<HTMLButtonElement>('[data-undo]').onclick = () => { const previous = history.pop(); if (!previous) return; future.push(snap()); project = JSON.parse(previous) as StudioProject; activeTriggerId = project.triggers[0].id; render(); void saveAll(); };
query<HTMLButtonElement>('[data-redo]').onclick = () => { const next = future.pop(); if (!next) return; history.push(snap()); project = JSON.parse(next) as StudioProject; activeTriggerId = project.triggers[0].id; render(); void saveAll(); };
query<HTMLButtonElement>('[data-home]').onclick = () => void openHomepage();
query<HTMLButtonElement>('[data-search]').onclick = () => showProjectSearch();
query<HTMLButtonElement>('[data-commands]').onclick = () => showCommandPalette();
query<HTMLButtonElement>('[data-toggle-project-panel]').onclick=()=>togglePanel('project');query<HTMLButtonElement>('[data-toggle-inspector]').onclick=()=>togglePanel('inspector');
query<HTMLSelectElement>('[data-language]').onchange=event=>{studioPreferences.locale=(event.currentTarget as HTMLSelectElement).value==='en'?'en':'es';void persistStudioPreferences(studioPreferences);render()};
const apiButton = app.querySelector<HTMLButtonElement>('[data-api]'); if (apiButton) apiButton.onclick = async () => { status('Consultando…'); try { status(await checkRemote()); } catch { status('API sin conexión'); } };
query<HTMLButtonElement>('[data-convert-lua]').onclick = (event) => { event.preventDefault(); try { const before = snap(), converted = importLua(query<HTMLTextAreaElement>('[data-lua-source]').value, project.id); converted.title = project.title; project = converted; activeTriggerId = project.triggers[0].id; query<HTMLDialogElement>('[data-lua-dialog]').close(); commit(before, 'Lua convertido a activadores'); } catch (error) { alert(error instanceof Error ? error.message : 'No se pudo convertir.'); } };
window.addEventListener('keydown', (event) => { const control=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if((event.target as HTMLElement|null)?.closest('input,textarea,select,[contenteditable="true"]'))return;if(event.key==='F1'||(control&&event.shiftKey&&key==='p')){event.preventDefault();showCommandPalette();return;}if(!control)return;if(key==='/'&&!event.altKey&&!event.shiftKey){event.preventDefault();showKeyboardShortcuts();return;}if(key==='b'&&!event.altKey&&!event.shiftKey){event.preventDefault();togglePanel('project');return;}if(event.altKey&&key==='i'){event.preventDefault();togglePanel('inspector');return;}if(event.shiftKey&&key==='f'){event.preventDefault();togglePanel('focus');return;}if(key==='k'){event.preventDefault();showProjectSearch();}if(key==='s'){event.preventDefault();void exportProject(project);}if(key==='z'){event.preventDefault();query<HTMLButtonElement>('[data-undo]').click();}if(key==='y'){event.preventDefault();query<HTMLButtonElement>('[data-redo]').click();}if(event.altKey&&key==='t'){event.preventDefault();query<HTMLButtonElement>('[data-add-trigger]').click();} });

studioPreferences=await loadStudioPreferences();query<HTMLSelectElement>('[data-language]').value=studioPreferences.locale;applyPanelLayout();projects = await listProjects(); if (projects.length) project = projects[0]; else projects = [project]; activeTriggerId = project.triggers[0]?.id || ''; render(); void saveAll();
